### ISSUE TITLE
type object 'TaggedSomething' has no attribute 'tags_for'

### ISSUE THREAD

**Issue by x1a0** [jazzband/django-taggit#101]
My class is inherited from `taggit.models.ItemBase`:

```
class TaggedSomething(ItemBase):
    content_object = models.ForeignKey('Something')
    tag = models.ForeignKey('MyTag')
```

However I got this error:
`type object 'TaggedSomething' has no attribute 'tags_for'.`

By digging the source it looks like `tags_for` is a mandatory class_method I need to implement. But I didn't see anywhere in the document. So I want to confirm it here.

**Comment by jackappleby** [comment]
Using taggit 0.17.1 I get "type object 'TaggedItem' has no attribute 'tags_for'". As far as I'm aware I'm not using a custom class. 

My code that causes the error is:

    def store_tags(apps, schema_editor):
        import tagulous
        model = apps.get_model('myapp', 'MyModel')
        for obj in model.objects.all():
            obj.tags_store = tagulous.utils.render_tags(obj.tags.all())

I've tried copying the tags_for method into various classes within the taggit code but it never finds it.

**Comment by radiac** [comment]
I think jackappleby's error is my fault - sorry. That's from a data migration I suggested in docs, but of course taggit won't be available there. It's therefore probably unrelated to the original issue.

**Comment by gregplaysguitar** [comment]
I've just been bitten by this; seems it should be as simple as moving the class method `tags_for` from `TaggedItemBase` into `ItemBase`? Any reason why this hasn't been fixed, or at least mentioned in the docs? I'm happy to fork and make the change

**Comment by naringas** [comment]
Maybe there's a reason not to move class method `tags_for` to `ItemBase` ??

Otherwise I think it should be done. I've had to repeat myself by copying that method to my custom Tag model.

**Comment by mwbennett** [comment]
+1 just ran into this issue as well. Seems silly to have to copy the class method to the inheriting object.

**Comment by dinoilic** [comment]
I have the same issue: `AttributeError: type object 'TaggedItem' has no attribute 'tags_for'`.

I encountered it while doing a data migration and this code causes it:
```python
for tag_name in challenge.tags.names():
    challenge_contest.tags.add(tag_name)
```

I tried several versions of the code, all of which seem to fail, and this particular code snippet fails on the first line. If I try doing it manually in shell I can get the list and iterate through it without any problems.

As far as I know I'm not using any custom models. Got any suggestions?

**Comment by br-nhan** [comment]
I have same problem when try to use taggeditem in migrations, and got the solution from here: https://stackoverflow.com/a/13827552/1463090
My code was written for Django 2.0:

```python
def forwards(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    TaggedItems = apps.get_model('taggit', 'TaggedItem')
    ct = ContentType.objects.get(app_label="news", model="article")
    for article in Article.objects.all():
        tagged_items = TaggedItems.objects.filter(
            content_type_id=ct.id,
            object_id=article.id  # Associates the Tag with your Post
        )
        tags = [tag.tag for tag in tagged_items.all()] # Get Tag object
        article.tags_in_string = comma_joiner(tags) # Custom comma joiner function
        article.save()
```

**Comment by virusvn** [comment]
I have same problem when try to use taggeditem in migrations, and got the solution from here: https://stackoverflow.com/a/13827552/1463090
My code was written for Django 2.0:

```python
def forwards(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    TaggedItems = apps.get_model('taggit', 'TaggedItem')
    ct = ContentType.objects.get(app_label="news", model="article")
    for article in Article.objects.all():
        tagged_items = TaggedItems.objects.filter(
            content_type_id=ct.id,
            object_id=article.id  # Associates the Tag with your Post
        )
        tags = [tag.tag for tag in tagged_items.all()] # Get Tag object
        article.tags_in_string = comma_joiner(tags) # Custom comma joiner function
        article.save()
```

**Comment by pope1ni** [comment]
For everyone following this, #506 should address this problem.

In the interim, there is a very simple workaround which I haven't posted here for some reason:

```python
import taggit

...

class ItemBase(taggit.models.ItemBase):

    class Meta:
        abstract = True

    # XXX: Workaround for sub-classing problem upstream.
    #      https://github.com/alex/django-taggit/pull/506
    tags_for = classmethod(taggit.models.TaggedItemBase.tags_for.__func__)

...
```
