### ISSUE TITLE
'Tag' object has no attribute 'tag' when pass obj.tags in form initial

### ISSUE THREAD

**Issue by lynx-r** [jazzband/django-taggit#102]
When I pass obj.tags in form's initial data like so:
form = ImageForm(initial={'tags': img.tags})
I get error:
'Tag' object has no attribute 'tag'

**Comment by KineticHub** [comment]
same here

**Comment by rtpg** [comment]
not 100% sure on this one, but think the thing you're supposed to do is `img.tags.all()` or something to actually get the value. please re-open if this isn't the issue (and if it still exists in the latest releases).
