### ISSUE TITLE
"Related Field has invalid lookup: icontains" in Admin when adding 'tags' to search_fields

### ISSUE THREAD

**Issue by manelclos** [jazzband/django-taggit#103]
I want to be able to search in the tags field, but when I add it to the search_fields option in the ModelAdmin I get an exception:

Django Version:     1.3.1
Exception Type:     TypeError
Exception Value:    Related Field has invalid lookup: icontains
Exception Location:     /usr/local/lib/python2.6/dist-packages/Django-1.3.1-py2.6.egg/django/db/models/fields/related.py in get_prep_lookup, line 141

**Comment by Tikam02** [comment]
@sarendsen please elaborate it's still not working same error
