### ISSUE TITLE
taggit fails when primary_key isn't int

### ISSUE THREAD

**Issue by traverseda** [jazzband/django-taggit#121]
If you're using, say, the title of a blog as your primary key, django-taggit fails. The error message is not terribly useful. If you search for "invalid literal for int() with base 10 taggit", a couple (well, three anyway) of people have had this problem and it doesn't look like anyone's figured it out before. It's definitely a frustrating one.

http://pastebin.com/s1dgABpT

**Comment by rtpg** [comment]
Yeah basically in this case you can use custom tag kinds to get stuff working well here. Going to close this out now
