### ISSUE TITLE
Taggit with Haystack search

### ISSUE THREAD

**Issue by kuyucakli** [jazzband/django-taggit#130]
Hi,

I am trying to use Haystack for searching in my project. When  i try to make tags TaggableManager field indexable i get error TaggableManager is not iterable error. How can i use taggit with Haystack?

**Comment by pyghassen** [comment]
The question is whether django taggit is compatible with haystack or not, I've been googling about this subject, and all I found is forsaken questions left form 2011.

Is it a good idea to use taggit with haystack or just tags as CharField will make us avoid the problem?

**Comment by pa-jama** [comment]
I have the exact same problem. happened after I upgraded to django 1.7, before taggit was working with haystack
