### ISSUE TITLE
parse_tags oddity

### ISSUE THREAD

**Issue by iivvoo** [jazzband/django-taggit#133]
Why is a single tag containing space handled differently with/without a comma? E.g.

(Pdb) print parse_tags("google io")
[u'google', u'io']

(Pdb) print parse_tags("google io,")
[u'google io']

I understand parse_tags is trying to be smart/make assumptions about how tags are split but I'd prefer more fixed, predictable behaviour.

**Comment by rtpg** [comment]
The docs [have a thing on this now](https://django-taggit.readthedocs.io/en/latest/forms.html), you can also [provide a custom string parser now](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#using-a-custom-tag-string-parser). 

There might be an argument to change the defaults now that we have a configuration thing, but that's a bit of a separate thing
