### ISSUE TITLE
Taggit as Admin Inline for model being tagged.

### ISSUE THREAD

**Issue by AnthonyBRoberts** [jazzband/django-taggit#136]
I tried to add the class TaggedItemInline(admin.TabularInline): to my admin.py, but class 'taggit.models.TaggedItem' has no ForeignKey to class 'apps.story.models.Article'

Can I have the taggit admin as an inline to the main admin.ModelAdmin?

**Comment by mfcovington** [comment]
@AnthonyBRoberts (or anyone else that has this issue):

    from taggit.models import TaggedItem

    class TaggedItemInline(GenericTabularInline):
        model = TaggedItem
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
        ordering = ('tag__name',)

**Comment by vesnikos** [comment]
it would be nice if there was a mention of this in the documents
