### ISSUE TITLE
Proper way to separate tags

### ISSUE THREAD

**Issue by jab3z** [jazzband/django-taggit#165]
Hello there,

Please tell me a proper way to separate tags in templates, as the builtin filter "join" doesn't work. I also tried a custom one:

{{ tags| joinby:", " }} 
def joinby(value, arg):
    return arg.join(value)

But instead of returning values comma seprated it returns each letter of a tag separated by value.

Thank you in advance.

Regards,
jab3z

**Comment by rtpg** [comment]
you should be able to do a `{% for tag in tags %}{{tag}},{% endfor %}` style thing (with the standard song and dance on the last comma)
