### ISSUE TITLE
Using custom tag/taggable item models without generic FK fails

### ISSUE THREAD

**Issue by mikek** [jazzband/django-taggit#169]
`develop` branch at 91791c87a99dc20a69174a958a388b10e4573860 contains docs on how to use custom models. It sounds like it is possible to avoid using content types and simplify the DB layout. The following code breaks on ModelForm rendering though:

```
class CustomTag(TagBase):
    description = models.CharField(_('description'), max_length=200)

class CustomTaggedItem(ItemBase):
    tag = models.ForeignKey(CustomTag,
                            related_name="%(app_label)s_%(class)s_items")

class Place(models.Model):
    title = models.CharField(_('description'), max_length=50)
    tags = TaggableManager(through=CustomTaggedItem)
```

The error is: `Cannot resolve keyword u'content_object' into field. Choices are: id, tag`. And it is triggered by `TaggableManager.value_from_object() -> ItemBase.lookup_kwargs()`. 

Tag lookups fail at another point: `TaggableManager.m2m_column_name()` triggers `CustomTaggedItem has no field named u'content_object'` error.

ItemBase obviously has no `content_object` field, which appears to be hardcoded upper in the hierarchy tree.

Are we expected at least to override `lookup_kwargs`, `tags_for` in any `ItemBase` subclass?

**Comment by rtpg** [comment]
I'm like 95% sure this doesn't exist as a problem naymore given how much custom tagging stuff I've done. Closing for now
