### ISSUE TITLE
django-taggit creating dozens of queries in admin panel when saving custom tag

### ISSUE THREAD

**Issue by mattandrews** [jazzband/django-taggit#170]
I posted about this on [StackOverlow](http://stackoverflow.com/questions/19837959/django-admin-creating-dozens-of-extra-queries-why-how-can-i-stop-it), but here it is in summary:

I have a `GenericTaggedItemBase` for my tagging through model so I can add an extra field to tags (a twitter username). I have a `post_save` hook which is supposed to check for tags added to content which have twitter usernames, and to post a tweet to those usernames with a link to the content.

When I save the content item and look in the Django Debug Toolbar I see it make some queries I've written in the `post_save` hook, but then some weirdness like this:

```
SELECT * FROM tag_mappings LIMIT 21
```

The following queries after that basically loop through the 21 results from the first query and looks up the tags.

There are more code samples on the StackOverflow question but this looks to be something django-taggit is doing. Here's a full screeshot:

![image](https://f.cloud.github.com/assets/394376/1549849/fd8f79b0-4df2-11e3-8da6-ebec3ef841f9.png)

Is this a known issue? I'm not sure if it happens without the custom through model or the `post_save` hook; happy to check.

**Comment by rtpg** [comment]
I'm not 100% sure what's the thing here, but it feels totally possible for there to be 20 queries when there could only be 1 on the admin list view (that is by default paginated by 20). I think someone might want to just build up a custom app to try this out and figure stuff out.

**Comment by mattandrews** [comment]
This is an ancient issue of mine, but in retrospect I'm fairly sure it was something weird on my end rather than django-taggit. I was doing all kinds of non-Django things because I was new to the framework (eg. running raw SQL queries as you can see in the linked StackOverflow post) via post-save hooks.

**Comment by rtpg** [comment]
thanks for piping in! Alright, I'm going to close this one out, and assume that was the case here. Only have so many hours in the day, and triaging 100+ issues took a while :)
