### ISSUE TITLE
tag saving does not play well with transaction.atomic

### ISSUE THREAD

**Issue by mjl** [jazzband/django-taggit#174]
The following code

```
    tags = [ 'some_Tag_that_alreay_exists_with_different_capitalisation' ]
    with atomic():
        someobject.tags.add(*tags)
```

explodes with a

**TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.**

As far as I see, this is caused by the loop in models.py:36, which tries to invent a new slug if it already exists and does savepoints and rollbacks. However, that kind of transaction handling does not seem to play well with transaction.atomic().

Perhaps taggit should dump the idea of differencing between tags with different capitalisation altogether (really want to have "Sales" and "sales" tags??) and just map them to the same item?

**Comment by rtpg** [comment]
0.16 fixes case sensitivity (https://django-taggit.readthedocs.io/en/latest/changelog.html?highlight=case#id37)
