### ISSUE TITLE
Two different models with TaggableManager field. Can't migrate data because of conflict

### ISSUE THREAD

**Issue by deronsizemore** [jazzband/django-taggit#183]
I've got two apps which I'm trying to use taggit. Each app has a TaggableManager model field called tags. I'm trying to sync the db using South, but am getting an error message:

CommandError: One or more models did not validate:
blog.post: Accessor for m2m field 'tagged_items' clashes with related m2m field 'TaggedItem.post_set'. Add a related_name argument to the definition for 'tagged_items'.
protalk.post: Accessor for m2m field 'tagged_items' clashes with related m2m field 'TaggedItem.post_set'. Add a related_name argument to the definition for 'tagged_items'.

Everything I've found online just says to give each field a related_name which I've tried but still getting the same errors. Any ideas on how to resolve this?

**Comment by rtpg** [comment]
Given south is no longer a thing, going to close this one out. I'll keep it in mind for other migration-related issues though
