### ISSUE TITLE
Rest Framework integration

### ISSUE THREAD

**Issue by Nicals** [jazzband/django-taggit#223]
Due to it's "managed" implementation, django-taggit is not easy to use with django-restframework.

Since I couldn't find anything but ugly and bad written hack on the internet to interface django-taggit with the rest framework, I think it would be a great thing to implement a working serializer for taggit. It could be either directly implemented into django-taggit or be an interface third-party application.

I'm not used to the rest-framework, but since I currently need this feature, I'm developing a small app to do the job. I may release it if I find it clean enough.

**Comment by allyjweir** [comment]
@xaralis I am trying to use your solution in my project but am running into issues. Can you spot any mistakes?

    from django.forms import widgets
    from core import serializers as custom_serializers
    from datapoint.models import Datapoint, Annotation
    from rest_framework import serializers


    class TaggedModelSerializer(serializers.ModelSerializer):
        """
        xaralis's solution from https://github.com/alex/django-taggit/issues/223
        
        Rest framework doesn't work with django taggit very well since it is not
        ready for fields being in fact TaggitManager instance.

        This class solves it by pulling out the incorrectly resolved data and saving
        them manually thereafter.
        """
        tag_fields = ['tags']

        def save_object(self, obj, **kwargs):
            tags_to_set = {}

            # Try to find tag data.
            if getattr(obj, '_m2m_data', None):
                for f in self.tag_fields:
                    if f in obj._m2m_data:
                        # pop() is important. We don't want the data to be set by
                        # rest framework.
                        tags_to_set[f] = obj._m2m_data.pop(f)

            # When data has been cleaned, save the object as usual.
            super(TaggedModelSerializer, self).save_object(obj, **kwargs)

            # If some tag data was previously found, save them now.
            for f, tags in tags_to_set.items():
                # Pull out the tag manager class.
                mngr = getattr(obj, f)

                # Decide which class for tags is being used.
                TagClass = mngr.through.tag.field.rel.to
                tgs = TagClass.objects.filter(slug__in=tags)

                # Finally, set the data using manager class.
                mngr.set(*tgs)


    class DatapointSerializer(TaggedModelSerializer):
        class Meta:
            model = Datapoint
            fields = ('pk', 'owner', 'project', 'collections', 'name', 'description', 'author', 'source', 'url',
                                                            'publish_date', 'tags')

**Comment by glemmaPaul** [comment]
I don't know if anyone is interested, but I've been working on a serializer for the django taggit package. Take a looksies and if you have any issues or changes you wanna make, let me know!

https://github.com/glemmaPaul/django-taggit-serializer

**Comment by philippeluickx** [comment]
Kudos @glemmaPaul ! Will definitely give this a go!

**Comment by dukeayers** [comment]
@glemmaPaul stellar job, I was afraid I would have to do some long, arduous task to get taggit and DRF to play nice. For anyone reading this, definitely use his serializer.

**Comment by stantond** [comment]
Are there any solutions for filtering from tags in a GET URL for DRF + Taggit?

**Comment by chandra-technicise** [comment]
I have used this serializer for DRF  + django-taggit - https://github.com/glemmaPaul/django-taggit-serializer it works fine..

**Comment by joshua-s** [comment]
Since this issue appears to be resolved, I am closing it. Please open a new issue for any new concerns.
