### ISSUE TITLE
Hide Taggit/tags on admin page?

### ISSUE THREAD

**Issue by mattandrews** [jazzband/django-taggit#271]
I'm using a custom tag base/model for my tags (so I can add fields to tags) and therefore have a separate model from the default `Taggit.tag` one (mine is called `ContentTag`). I converted the default taggit model to this new one so my system still shows the Taggit admin screen like so:

![screen shot 2014-10-07 at 9 42 07pm](https://cloud.githubusercontent.com/assets/394376/4549952/6e0888ba-4e62-11e4-869a-73977bac27ff.png)

Is there a way of removing this from the admin panel? It's confusing users as the actual place they administer tags is my new `ContentTag` model. 

I may be misunderstanding the custom tag base option here so apologies if so.

**Comment by Braintelligence** [comment]
To leave a clean answer for anyone that is trying to find this out:

In your admin.py:
```python
from taggit.admin import Tag

admin.site.unregister(Tag)
```

That's it.
