### ISSUE TITLE
Customizing the tagged item page (Admin)

### ISSUE THREAD

**Issue by nlj24** [jazzband/django-taggit#314]
Hello, I hope I'm not missing something easy! I successfully installed the taggit application and now I can add tags to one of my classes (class Person). So on the page in the admin where I view the person, I can see and edit the comma separated list of tags, which is great. When I go to the tags section of the admin site, I have the following situation. Say I have two objects, Person1 and Person2 that both have the tag 'boy'... When I go into the admin page and view the 'boy' tag object, I can successfully see that both Person1 and Person2 are objects associated with that tag.

I would like to customize the look of that page. I currently see the listed objects as Person1, object id = 123, and then type = Person. Similar for the next item, which is Person2. This is great, but I would like to just see the names Person1 and Person2 and get rid of that other information.

It would be fantastic if it were possible to make Person1 and Person2 links that went to the admin pages for them as well!

Thanks for any help and for a great app!

**Comment by rtpg** [comment]
this is more of a django admin customization problem, not so much a django-taggit thing. The django docs have stuff on how you can customize what shows up on admin pages, and things like adding links. It's a bit hard for me to go into detail here for you though
