### ISSUE TITLE
Templatetag get_tagcloud outputs an error when only one tag in db

### ISSUE THREAD

**Issue by synw** [jazzband/django-taggit#323]
When there is only one tag in the database the templatetag  {% get_tagcloud as tags %} gives a "ZeroDivisionError at / float division by zero"

Remove the only tag or add one more and the issue is gone

**Comment by tykling** [comment]
I get this error too, but with several tags and items in the DB.

**Comment by rtpg** [comment]
this isn't a feature of `django-taggit` but of `django-taggit-templatetags`
