### ISSUE TITLE
Race condition with get_or_create on TaggedItem

### ISSUE THREAD

**Issue by mythmon** [jazzband/django-taggit#349]
When adding tags to items, the `TaggedItem` model is used for the intermediate table. In particular, `get_or_create` is used. There are no unique restrictions on this table, so [`get_or_create` is vulnerable to race conditions](https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create) if two threads/processes/servers try and add a tag to one item at the same time.

To fix this, I think it would work to add a unique_together contrainst on `(tag, content_type, object_id)` on the TaggedItem model. That way, the second creation will not happen (and `get_or_create` will recover correctly).

**Comment by frewsxcv** [comment]
Thanks for pointing this out! If you create a pull request for this, I'd be happy to merge it

**Comment by mythmon** [comment]
I filed a partial PR for this, but I'm having some trouble with migrations. I didn't see any examples or documentation about migrations. Can you provide some help in that PR?
