### ISSUE TITLE
Passing ordering parameter to the TaggableManager

### ISSUE THREAD

**Issue by Natim** [jazzband/django-taggit#370]
So far I am doing it like this:

```
class _SortedTaggableManager(_TaggableManager):
    def get_queryset(self, *args, **kwargs):
        qs = super(_SortedTaggableManager, self).get_queryset(*args, **kwargs)
        return qs.order_by("name")
```

Then later in the code I am defining the following:

```
tags = TaggableManager(manager=_SortedTaggableManager)
```

But I feel it would be much easier to simply write:

```
tags = TaggableManager(ordering=["name"])
```

What do you think?

**Comment by queiroz** [comment]
Why not simply order from the Django template `{% for tag in post.tags.all|dictsort:"name" %}`?

**Comment by nicorellius** [comment]
It's almost always better to sort or order at the model level, then the view level, and lastly at the template level. I'm currently struggling with custom tags and related models not honoring the `ordering` option the `Meta` class. In my case, I'm tagging things that need to be grouped and ordered by tag, so this is important to me.

**Comment by rtpg** [comment]
@nicorellius do you have a sample snippet where the `ordering` isn't respected on a custom tag? That seems like a relatively easy fix

**Comment by kavdev** [comment]
Just throwing this out there for anyone who comes across this looking to solve ``prefetch_related`` query issues.

The taggable manager has a workaround in the ``get_queryset`` that helps avoid spawning a ton of queries. Removing that causes a specified ``prefetch_related`` to both send the prefetch query and then still fetch tags on each instance.

Here's a version of @Natim's manager that supports ``prefetch_related``. I've submitted a version of this as a PR.

```python
class _SortedTaggableManager(_TaggableManager):
    ordering = ["name"]

    def get_queryset(self, extra_filters=None):
        try:
            return self.instance._prefetched_objects_cache[self.prefetch_cache_name]
        except (AttributeError, KeyError):
            kwargs = extra_filters if extra_filters else {}
            return self.through.tags_for(self.model, self.instance, **kwargs).order_by(*self.ordering)
```
