### ISSUE TITLE
.slugs() and .names() doesn't work for (Generic)TaggedItemBase custom tags

### ISSUE THREAD

**Issue by Braintelligence** [jazzband/django-taggit#377]
Hello everyone.

So I created a model with Custom Tags:

``` python
class ArticleTaggedItemBase(TaggedItemBase):
    content_object = models.ForeignKey('Article')

class Article(models.Model):
    title = models.CharField(max_length=300)
    comment = models.CharField(max_length=600, blank=True)

    tags = TaggableManager(through=ArticleTaggedItemBase)
```

When trying

``` python
Article.tags.all()
```

in the manage.py shell it works and returns a list of Tag objects.

When trying

``` python
Article.tags.names()
Article.tags.slugs()
```

both methods return this error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "my\dir\to\virtualenv\lib\site-packages\taggit\utils.py", line 138, in inner
    raise TypeError("Can't call %s with a non-instance manager" % func.__name__)
TypeError: Can't call names with a non-instance manager
```

Where it says can't call names it says can't call slugs for the slugs error.

Any ideas?

**Comment by Braintelligence** [comment]
Update: This also occurs for me when using the standard TaggableManager()!

**Comment by philgyford** [comment]
I've no idea if this is the solution, but you might want to try adding `related_name` to the `content_object`:

    class ArticleTaggedItemBase(TaggedItemBase):
        content_object = models.ForeignKey('Article', related_name="%(app_label)s_%(class)s_items")

Only because I have a similar setup and `names()` and `slugs()` work fine for me, and this looked like the main difference we have.

**Comment by rtpg** [comment]
as the error message says you need an instance manager (like `Article.objects.get(pk=1).tags.names()`). Probably need to improve the error message here
