### ISSUE TITLE
Trying to pass data to the GenericTaggedItemBase

### ISSUE THREAD

**Issue by mikewolfd** [jazzband/django-taggit#453]
I'm currently trying to use taggit's custom tag feature. 

I've run into an issue where I want to keep track of who tagged what and when. 

So when I add tags to a LabeledObject it would also pass user data to the GenericTaggedItemBase. Is there an easy way to pass data through taggablemanager to do so?

```
class Label(TagBase, TimeStampedModel):

class LabeledItem(GenericTaggedItemBase, TimeStampedModel):
    user = models.CharField(max_length=255)
    tag = models.ForeignKey(Label,
                            related_name="%(app_label)s_%(class)s_items")

class LabeledObject(models.Model):
    object = models.OneToOneField('object')
    labels = TaggableManager(through=LabeledItem)
```

**Comment by mikewolfd** [comment]
Figured it out. Added this to my LabeledItem model.

```
    @classmethod
    def lookup_kwargs(cls, instance):
        return {
            'object_id': instance.pk,
            'content_type': ContentType.objects.get_for_model(instance),
            **'user': instance.user**
        }
```

**Comment by rtpg** [comment]
[`tag_kwargs` should give you what you want](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html?highlight=tag_kwargs#custom-tag)
