### ISSUE TITLE
django-taggit-anywhere

### ISSUE THREAD

**Issue by bashu** [jazzband/django-taggit#458]
Hey,

Thanks for django-taggit app and here is my small contribution https://github.com/bashu/django-taggit-anywhere

Q: is it worth mentioning in docs?

**Comment by frewsxcv** [comment]
Hey @bashu! If you'd like to, you can open a pull request and add your library on this page: https://github.com/bashu/django-taggit-anywhere

**Comment by nemesisdesign** [comment]
@bashu this is the file you can edit to add a link to your third party app:
https://github.com/alex/django-taggit/blob/master/docs/external_apps.txt
