### ISSUE TITLE
if there is no trailing comma in form - single item becomes separate tags

### ISSUE THREAD

**Issue by rafirosenberg** [jazzband/django-taggit#474]
if i create a tag, using a form, with one single item, and no trailing comma, each word becomes a separate tag.
e.g
i want to tag = i, tag, to , want
but: i want to tag, = i want to tag
and i want to tag, now = i want to tag, now

I am using django 1.10.3, python 2.7.12, and django-form-utils

**Comment by rtpg** [comment]
[this behaviour is documented here](https://django-taggit.readthedocs.io/en/latest/forms.html), you can override it as well
