### ISSUE TITLE
Django Taggit cant save through admin

### ISSUE THREAD

**Issue by morpheusp2p** [jazzband/django-taggit#493]
I am having a small issue with django admin and django taggit, when i try to save tags through django admin save_model function in my ModelAdmin class it saves the tagged element and then removes it or overwrites the element later on. There is no error with the code it just overwrites the entry later on with the value for tags in forms.

I want to be able to add tags through the ModelAdmin class as i am fetching the keywords through the meta content of the link present in the model Content_Master. The get_metadata function is returning me meta keywords from the url given. Any help on this would be a big help. Thanks !

Models.py

class Content_Master(models.Model):
        ...
        content_link = models.URLField(default=None, null=True, blank=True,unique= True)
        tags = TaggableManager(blank=True)

Admin.py

def save_model(self, request, obj, form, change):
        keyword = get_metadata(identifier = obj.content_link)
        obj.save()
        artic = Content_Master.objects.filter(content_title = title,published_date = time).values('content_id')
        art1 = artic[0]
        art = art1.values()[0]
        co = ContentType.objects.get(model="content_master")
        if keyword is not None:
            tagg = keyword.split(',')
            #print tagg
            for taggs in tagg:
                tag, created = Tag.objects.get_or_create(name = taggs)
                tagged = TaggedItem(object_id=art, tag=tag,content_type=co)
                #print tagged
                tagged.save()

**Comment by rtpg** [comment]
this is built-in functionality in the `save` method I believe, not sure this is really incorrect behaviour.
