### ISSUE TITLE
Reverse Query Name Clash

### ISSUE THREAD

**Issue by tors10e** [jazzband/django-taggit#494]
With a model class called  Name, taggit returns an error.

class example:
```
class Name(models.Model):
    ... fields
    tags = TaggableManager(related_name="a_unique_related_name")

```
Error:

>  appname.Name.tags: (fields.E303) Reverse query name for 'Name.tags' clashes with field name' Tag.name'.
> 	HINT: Rename field 'Tag.name', or add/change a related_name argument to the definition for field 'Name.tags'.

**Comment by torstenernst** [comment]
I fixed this by changing the related_query_name definition of TaggableManager class to:

```
    def related_query_name(self):
        #return self.model._meta.model_name
        return self.remote_field.related_name
```
I'm not familiar with this project, so I don't know the implications of this change, but so far so good.
