### ISSUE TITLE
Trying to implement user owned tags in django-taggit for specific objects

### ISSUE THREAD

**Issue by gilgameshskytrooper** [jazzband/django-taggit#507]
I am trying to implement a Video model in Django 1.11 which are tagged by both global tags (which are added by the admin when the video is first uploaded) which are able to be viewed by everyone accessing, and user specific tags (added by users per video) which are specific to the user logged in.

Currently, the model looks something like this:

```
class Video(models.Model):
    video_name = models.CharField(max_length=50)
    video_pub_date = models.DateTimeField('date published')
    video_file = models.FileField()
    video_thumbnail = models.ImageField(null=True, blank=True)
    global_tags = TaggableManager()
    video_views = models.IntegerField(default=0)
```

User model is just using from django.contrib.auth.models import User but not explicitly defined in my ```models.py``` file

However, in addition to global_tags, I need a way to have private tags (user specific). [This answer](https://stackoverflow.com/questions/11321906/in-django-taggit-how-to-get-tags-for-objects-that-are-associated-with-a-specifi) shows how to get tags for objects that are associated with a specific user, but this is not what I want since the object themselves (in my case Video), is not owned by anyone in particular, but the tags themselves are to be owned by specific user.

**Comment by joaaogui** [comment]
@gilgameshskytrooper did you ever solve that problem ? If yes, how ?

I have the same need

**Comment by joaaogui** [comment]
Thanks anyway

**Comment by olleugra** [comment]
My solution was to adapt django taggit as a local app. then I modified the TagBase to remove the uniqueness for 'name' and 'slug' fields. I also added a user foreignkey.
`class TagBase(models.Model):`
user = models.ForeignKey(User, null=True, on_delete=models.CASCADE,related_name='tagbaseuser')`
`name = models.CharField(verbose_name=_("Name"), unique=False, max_length=100)`
`slug = models.SlugField(verbose_name=_("Slug"), unique=False, max_length=100)`

**Comment by gilgameshskytrooper** [comment]
This feels a bit backstabby to Django, but for the past 2 years, I've used idomatic Go to write my backends [for both work and personal projects] (rolling my own native SQL queries using the Go std lib without ORM's etc.) and I've never looked back.

Basically in my experience, once you write your Django app, you still have to put in a significant effort in optimizing your backend to maximize cores by using a WSGI, managing dependency during production execution. However, with Go, the default `go build` command builds a production ready fully non-threaded backend executable that you can just start running, and reverse proxy requests to (which is far easier to manage during production execution).

At the same time, because of the strong support for most backend related logic in the standard library, you can always r.y.o model classes no problem

I would encourage anyone having trouble Django or Rails to check out Go.

**Comment by PeteAndersen** [comment]
Unrelated discussion aside, I've been finding custom tag models very hard to use in practice. It's very easy to design them, but using the extra fields is not possible without overriding all of the manager methods in `_TaggableManager`, particularly the `_to_tag_model_instances()` method, to support putting values into these extra fields. Using nullable fields and setting the values later is not desired and feels like a hack. Some way to pass in tag model kwargs to be set when using `add()` or `set()` would be fantastic.

Here's what my ideal application code would look like with easy support for custom tag fields:

Models:
```python
class MyCustomTag(TagBase):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=100, db_index=True)  # Override to remove unique requirement
	slug = models.SlugField(max_length=100, db_index=True)  # Override to remove unique requirement

class TaggedFood(TaggedItemBase):
	content_object = models.ForeignKey('Food', on_delete=models.CASCADE)
	tag = models.ForeignKey(MyCustomTag, on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_items")

class Food(models.Model):
	# ... fields here
	tags = TaggableManager(through=TaggedModel)
```

Usage:

```python
>>> owner = User.objects.first()
>>> food = Food()
>>> food.tags.add('tasty', 'chewy', tag_kwargs={'owner': owner})
```

I believe this could be accomplished fairly easily by passing these kwargs into `_to_tag_model_instances()` and merging it with the default get_or_create calls. I'll give it a go and see how it ends up working in practice.

**Comment by rtpg** [comment]
I don't really think this is a Go/Django/anything problem, this is mostly a database design problem.

Let's say you have your public videos, and private user annotations. Really since you don't want to mix the users' annotations together, you probably want to make a through table, like

```python
class PrivateAnnotations(models.Model):
    video = models.ForeignKey(Video)
    user = models.ForeignKey(User)
    tags = TagManager()  # if you want private non-shared tags you can add a custom through table
```

So the private data isn't all mixed together, you still have your videos being shared, and you can work on stuff "cleanly". No magic needed.

btw @olleugra's solution is also OK, tho really you could ust make a `CustomTaggedItem` and then make your own homespun `Tag` (`django-taggit` really doesn't have much in terms of restrictions on tags when you get into custom territory)
