### ISSUE TITLE
KeyError with `similar_objects()` function

### ISSUE THREAD

**Issue by DDiran** [jazzband/django-taggit#508]
Hi Alex,

I'm working on a project using `Wagtail-CMS` which incorporates your tagging system. For what I'm working on at the moment the `similar_objects()` function you created is exactly what I need, however I think there might be an issue with the function (unless I'm making some silly mistake in my own code).

I've written up a detailed post on SO which you can check out [here](https://stackoverflow.com/questions/47240510/getting-related-objects-via-tags-in-django).

Many thanks

**Comment by prokaktus** [comment]
Stuck with the same problem. Eventually I decided to use `raw` sql to perform my query. I wrote this way (It is just **workaround**, not solution to original problem.):
```
ArticlePage.objects.raw('select a.page_ptr_id, p.title, count(at.tag_id) as tag_count from article_articlepage a join wagtailcore_page p on a.page_ptr_id = p.id join article_articletag at on at.content_object_id = a.page_ptr_id join taggit_tag t on t.id = at.tag_id where tag_id in (1, 2, 3) group by (page_ptr_id, p.id) order by tag_count desc');
```

I put this into gist with better explanation, so feel free to copy and modify it if you needed: https://gist.github.com/prokaktus/bd805e3f9a3eabb64be22523ae5fdf66

**Comment by legshort** [comment]
I'm having the same issue and seems like this pr #424 is kind of stuck for the last few years.

**Comment by jaap3** [comment]
This seems to be a duplicate of #80

**Comment by jdufresne** [comment]
Thanks.
