### ISSUE TITLE
Release django 2.0, mailing list and maintenance

### ISSUE THREAD

**Issue by nemesisdesign** [jazzband/django-taggit#520]
To the attention of maintainers @frewsxcv @alex (not aware who else is maintainer).

- can we release a new version on pypi? I merged some patches that were highly demanded lately
- I sent an email to the mailing list of django-taggit a few days ago to ask this but I believe is held for moderation - I don't think this moderation filter is a good thing if moderators don't have time to review it in a timely manner, I propose to turn it off
- can we make it a bit more clear somewhere regarding to who has github write access and who has pypi write access? This way occasional contributors can ping the right people to ping when they think something should be addressed urgently

Have a happy winter / Christmas Holiday!

Best regards
Federico

**Comment by frewsxcv** [comment]
> can we release a new version on pypi? I merged some patches that were highly demanded lately

thanks for stepping up and helping out with maintenance! i just invited you to be a maintainer for the package on pypi so you _should_ have publishing permission. let me know if i didn't set it up correctly

> I sent an email to the mailing list of django-taggit a few days ago to ask this but I believe is held for moderation - I don't think this moderation filter is a good thing if moderators don't have time to review it in a timely manner, I propose to turn it off

i haven't ever used the mailing list and i don't have access to maintain it, so this is something alex might need to disable

**Comment by pincoin** [comment]
Hello,

I installed `django-taggit` (0.22.1) using `pip install`.

The version 0.22.1 is the same version as git source repository, but `taggit/manager.py` file does not have the line 39:

https://github.com/alex/django-taggit/blob/master/taggit/managers.py#L39

That's why I still encounter the same issue #437 

Please, get your pypi package updated with the GIT source.

Merry Christmas, and Thank you.

**Comment by nemesisdesign** [comment]
@frewsxcv how can we get in touch with @alex to solve the ML problem?

**Comment by nemesisdesign** [comment]
@pincoin released, let me know if all is fine

**Comment by pincoin** [comment]
@nemesisdesign 

It works fine with Django 2.0. Thank you for your quick response.

**Comment by jpic** [comment]
Just in time for next dal release :guitar:

**Comment by jdufresne** [comment]
If you're looking for a hand maintaining the project, I'm willing to help. If the original authors have moved on or no longer have the time, maybe consider moving the project Jazzband.

**Comment by aaugustin** [comment]
I also believe that Jazzband could be a good solution for this project.

**Comment by jdufresne** [comment]
django-taggit 0.23.0 was released 2018-08-07 and the project has moved to Jazzband :tada: If you have any future issues, please leave a comment or open a new issue.
