### ISSUE TITLE
TagWidget's  attributes not working 

### ISSUE THREAD

**Issue by meibassam** [jazzband/django-taggit#529]
I'm Working on project using `Taggit` 
Model : 
```
class Topic(models.Model):
.......
    tag = TaggableManager()
```

Model Form : 
```
class TopicForm(forms.ModelForm):
    class Meta:
        model = models.Topic
        fields = [..., 'tag']
        widgets = {
            "tags":TagWidget(attrs={'placeholder':'Tags', 'class':'form-control'}),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }
```

But for sorry html classes of tags not working, in another side title html's class working perfectly, May I know what is the wrong thing I did ?

**Comment by bassamghouzi** [comment]
I know my problem is not that big, May find a quick response ?

**Comment by rtpg** [comment]
I'm not sure, but I think this stuff would work in more recent Django stuff, now that a lot of the form customization is built in? Please re-open if this is still an issue for you
