### ISSUE TITLE
how can i putput all tags  at  once？

### ISSUE THREAD

**Issue by reBiocoder** [jazzband/django-taggit#549]
how can i putput all tags  at  once？

**Comment by abhishekrai-kiwi** [comment]
maybe you wanna have a look at fixtures and loaddata

**Comment by rtpg** [comment]
depends on usage, stuff like `Tag.objects.all()`, things like fixtures as well will work. Very dependent on what you are going to do with the info, and what you mean by "all tags" and "output".
