### ISSUE TITLE
similar_objects query slow in MySQL for large data sets (suggested fix included)

### ISSUE THREAD

**Issue by joshmaker** [jazzband/django-taggit#57]
I've created a branch (https://github.com/joshmaker/django-taggit) that resolves performance issues that we were having on our MySQL database when making similar_object queries.

First, I added a parameter that allows users to [pass a limit to the query.](https://github.com/joshmaker/django-taggit/commit/fe49ea880d80d92c6282665c71c8655faa9c806b)

Having to pull thousands of tagged items was a major performance bottle neck.

Second, I broke the actual query itself into [two separate queries.](https://github.com/joshmaker/django-taggit/commit/0b1faf1560a604206537f34965d99771f7c93c5f)

The old method with a subquery prevented MySQL from using an index and resulted in a much slower query.  (In my tests, one 140ms query vs two 5ms queries)

**Comment by melinath** [comment]
+1

**Comment by pa-jama** [comment]
+1

**Comment by rtpg** [comment]
Going to close this one given the age (so not sure how much it still applies), but I think this falls a bit in the "extra params for `similar_objects`" category #709
