### ISSUE TITLE
Changing tagging permissions

### ISSUE THREAD

**Issue by bbaker6225** [jazzband/django-taggit#574]
Hello, I see in my admin page that django-taggit supports permissions for adding, changing, and deleting tags as well as tag items. Is there a guide for how to change this on a custom basis? For example, how could I configure this so only certain groups of staff users could add a new tag, but they could add existing tags to a model that supports tagging.

Thanks

**Comment by jdufresne** [comment]
Are you referring to Django's default builtin user and group permissions as documented here?

https://docs.djangoproject.com/en/2.1/topics/auth/default/#permissions-and-authorization

django-taggit has no special interaction with these and so normal Django rules apply.
