### ISSUE TITLE
Tags only visible in templates when in edit mode

### ISSUE THREAD

**Issue by g-mu** [jazzband/django-taggit#575]
I'm having an issue where I output tags into a template and they only show up when I'm in edit mode. When I log out or view the published page they don't show up. I have published the page several times but the tags don't seem to get published or something. I also see the linkages in sqlite.

I am using taggit_selectize and taggit_templates2, but removing those didn't change the behavior. You'll also see I have two properties in my model... the icon one works as expected.

Thanks for your help!

Here's my model:

```
from django.db import models
from cms.extensions import PageExtension
from cms.extensions.extension_pool import extension_pool
from taggit_selectize.managers import TaggableManager

class AttributeExtension(PageExtension):
    icon = models.CharField(
            max_length=48,
            verbose_name="Menu Icon",
            default='error')
    tags = TaggableManager(blank=True)

extension_pool.register(AttributeExtension)
```

And a simplified version of my template:

```
{% load cms_tags menu_tags sekizai_tags static taggit_templatetags2_tags %}
<!doctype html>
<html>
    <head></head>
    <body>
        {% cms_toolbar %}
        {% include 'includes/header_bar.html' %}
        <div class="container">
            <div class="page-content">
                <div class="page-content-container scrollable">
                    <div>{% block content %}{% endblock content %}</div>
                    <footer>
                        {% static_placeholder 'footer' %}
                        <br>
                        {% for tag in request.current_page.attributeextension.tags.all %}
                            {{ tag }}
                        {% endfor %}
                    </footer>
                </div>
            </div>
        </div>
        </div>
        {% render_block "js" %}
    </body>
</html>
```

**Comment by jdufresne** [comment]
Can you provide a minimal test case that doesn't include those other libraries (for example no cms, taggit_selectize, taggit_templatetags2_tags, etc.)

**Comment by rtpg** [comment]
it's been a while, going to close this. If anyone elsee lands on this and has a similar question or more info, please re-open this.
