### ISSUE TITLE
TaggableManager has a race condition

### ISSUE THREAD

**Issue by mixxorz** [jazzband/django-taggit#576]
Specifically, in the `_to_taggable_model_instances` method.

https://github.com/alex/django-taggit/blob/d4b6f1104de2d9afe6ac4232fccb9546f496f41e/taggit/managers.py#L188-L194

If a new tag is added to two TaggedItems at the same time, `.create` will raise an IntegrityError complaining about the uniqueness constraint.

The fix is to rewrite this section using `get_or_create` which handles this race condition.

I will submit a PR shortly.

**Comment by jdufresne** [comment]
Fixed in a4fd36f0ccb8b70e07ad9e4c7abefd68a8616c43 and released in 0.24.0. So clsoing.

#588 makes the necessary fields unique which should make the situation even more robust once complete.
