### ISSUE TITLE
Release soon please so we can get Django 2.1 support

### ISSUE THREAD

**Issue by collinanderson** [jazzband/django-taggit#587]
Hi All,

Could you please make a new release? I can't upgrade to Django 2.1 until django-taggit releases, and Django 2.2 is almost out which means my Django 2.0 version will be unsupported soon. There are some django 2.1 issues that have been fixed since the latest version 0.22.2 (released in 2017)

Thanks,
Collin

**Comment by jdufresne** [comment]
Hi Collin, version 0.23.0 added support for Django 2.1 and was released on 2018-08-07. Have you given this version a try or discovered a new bug that wasn't covered by that release?

**Comment by collinanderson** [comment]
Ahh I see I was looking here and thought the latest release was 0.22.2. Thanks!

https://github.com/jazzband/django-taggit/releases
