### ISSUE TITLE
Not saving words as tag name, instead saving each letter as a tag name

### ISSUE THREAD

**Issue by amcipher** [jazzband/django-taggit#598]
When I insert tags like **python, php** it saves each letter including comma (see below) as the tag name
p
y
t
h
o
n
,
p
h
p

**Comment by jdufresne** [comment]
Thanks for the bug report, but there is not enough information in this for me to reproduce. Please include the django-taggit version and minimal sample code to reproduce. If you can't create minimal sample code, please provide a minimal project with full steps to reproduce.

**Comment by rtpg** [comment]
you might be hitting the [string->tag behaviour documented in the docs](https://django-taggit.readthedocs.io/en/latest/forms.html). This isn't enough info for us to go on, so I'm going to close this. Please re-open if you have more information to provide here.

**Comment by majormunky** [comment]
I was able to re-create the problem of my tags being created as letters by trying to customize fields in my form in this manner:

```
class Testform(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    class Meta:
        fields = ["tags"]
        model = models.TestModel
```

If I move the customization of the tags field into the Meta class, this doesn't happen:
```
class Testform(forms.ModelForm):
    class Meta:
        fields = ["tags"]
        model = models.TestModel
        widgets = {"tags": forms.TextInput(attrs={"class": "form-control"})}
```
