### ISSUE TITLE
No matching distribution found for dajngo_taggit

### ISSUE THREAD

**Issue by mohamed591195** [jazzband/django-taggit#600]
this error appears when i am trying to install it via pip 

Could not find a version that satisfies the requirement dajngo_taggit (from versions: )
No matching distribution found for dajngo_taggit
i don't know the reason 

pip 19.0.3
python 3.7
manjaro linux based on arch --updated for the date of this post

**Comment by jdufresne** [comment]
There is a typo in the name: dajngo_taggit -> django_taggit

Is that the problem?

**Comment by mohamed591195** [comment]
what's the info you need ? 
could you tell me
