### ISSUE TITLE
 No module named 'taggit'

### ISSUE THREAD

**Issue by Oratoria** [jazzband/django-taggit#613]
I installed Django-taggit by pip. My Django version is 2.1. and my Python version is 3.7.

When i try to put "taggit" in installed app in setting.py, I got an error. 
ModuleNotFoundError: No module named 'taggit'

please help, Thank you.

**Comment by auvipy** [comment]
did you add that to the installed_apps list?

**Comment by Oratoria** [comment]
sorry, i solved by my self. i missed understand that my server was 3.7. my version was 2.7 and i was a little bit confused. now I understand. Thank you for the reply.
