### ISSUE TITLE
Online documentation changelog not up to date

### ISSUE THREAD

**Issue by KyeRussell** [jazzband/django-taggit#614]
The changelog page of the online documentation (https://django-taggit.readthedocs.io/en/latest/changelog.html) appears to be missing notes for all versions released prior to `0.23.0`. Whereas according to PyPI there has been a few releases since them.

Is there a reason for this, or was it just oversight?

**Comment by jdufresne** [comment]
Thanks for bringing this to my attention. Right now it is out of my hands so I've elevated this to the Jazzband project here:

https://github.com/jazzband/roadies/issues/140

**Comment by jdufresne** [comment]
Thanks for reporting. This has been fixed. If you continue to experience any issues with the docs, please let me know.
