### ISSUE TITLE
GenericTaggedItem.tags_for() no longer works on proxy models

### ISSUE THREAD

**Issue by mailbackwards** [jazzband/django-taggit#622]
While upgrading taggit from 0.x, I discovered that [this commit](https://github.com/jazzband/django-taggit/commit/5c2d0425221fd15a160cdb5606be67a53128e7e9) changed the syntax for fetching through the TaggableManager in a way that breaks proxy models looking through generic tagged items. For instance, I have an `Article` model that is a proxy subclass of `Page`. When I run `page.tags.all()`, I see all of my tags, but the same page's proxy `article.tags.all()` yields 0 results. It looks like the `ContentType.object.get_for_model`, and especially its `for_concrete_model=True` argument, was crucial in order for proxy models to work.

For now I will work around this by writing my own `tags_for` method that reverts to the old behavior, but wanted to file an issue here since I did not see a note about proxy instances in the docs, or a note that this might be a breaking change. Thanks, let me know if I can help with anything more concrete.

**Comment by jdufresne** [comment]
Thanks for the report! This was certainly not intentional. Are you up for writing a fix as a PR?

**Comment by mailbackwards** [comment]
Probably-- I will look into it soon. Thanks!

**Comment by jdufresne** [comment]
Closed via f06b40c206e599a33b2a128e4091ff90fca8c4d6
