### ISSUE TITLE
The Model._meta.virtual_fields attribute is removed in Django 2.0

### ISSUE THREAD

**Issue by DmytroLitvinov** [jazzband/django-taggit#624]
`virtual_fields` attribute is removed in [Django 2.0](https://docs.djangoproject.com/en/2.2/releases/2.0/)

https://github.com/jazzband/django-taggit/blob/f06b40c206e599a33b2a128e4091ff90fca8c4d6/taggit/managers.py#L550

If you need help with removing it to `private_fields` let me know I will prepare PR.

**Comment by jdufresne** [comment]
> If you need help with removing it to private_fields let me know I will prepare PR.

That would be great, thanks!
