### ISSUE TITLE
Tag field always appears as 'changed' in Django forms (contains patch)

### ISSUE THREAD

**Issue by alunbestor** [jazzband/django-taggit#63]
django-taggit's custom TagWidget always reports to Django's form classes that it has changed. This results in the django-admin logs claiming that the tag field has been modified, even when the value is left the same.

(This bug is present in django-taggit 6c6936eff36c143ed9eb9e584ddb4717ae0ab712, and tested against Django 1.2.5 and 1.3 beta 1 SVN-15323.)
#### Why this is happening:

To determine whether a field has changed, Django's BaseForm asks the field's widget to compare its initial value (the value from the model/initial dictionary) to _the raw value submitted to the form before clean() has been called._ In TagWidget's case this means it's comparing a tag manager to a string, which is always unequal.
#### Solution:

This can be fixed by customising the TagWidget's _has_changed method to normalise both values to strings before comparing them, and I'm attaching a patch that does that.

(This smells like a misfeature in Django, in that it ought to be checking against cleaned_data for changes; but I expect there's a lot of existing behaviour that depends on it checking against the raw values instead, so it probably won't get fixed upstream in Django. Even if it does, the revised method should be safe.)

**Comment by rtpg** [comment]
This one seemse to have been fixed in `TagField`, closing

**Comment by rtpg** [comment]
(there are tests pressent in `tests/test_forms.py`)
