### ISSUE TITLE
TaggableManager Doesn't Update Before Django post_save Signal is Fired

### ISSUE THREAD

**Issue by selected-pixel-jameson** [jazzband/django-taggit#639]
TaggableManager Doesn't Update Before Django post_save Signal is Fired.

I'm trying to use taggit to update search indexes on database rows. When an item is saved I want to read the new tags that are saved and use them to create the search_index that is stored within the row. However, when you try to reference model.tags.all() it is always out of date. So in turn you have to save the model twice through the Django Admin to get it to actually have the correct values when you are trying to hook into the saving of a model from the Django Admin Interface. 

I've run raw database queries to verify that the data is not updated in the database. I though it might just be being cached with Django's querying system. 

This seems like a bug as it seems like this is a very practical application for this.

**Comment by oma0256** [comment]
@selected-pixel-jameson I think instead of a `post_save` signal you should use the `m2m_changed` signal instead. [Docs](https://docs.djangoproject.com/en/2.2/ref/signals/#m2m-changed) on `m2m_changed` signal.
