### ISSUE TITLE
method get_queryset()

### ISSUE THREAD

**Issue by podushka** [jazzband/django-taggit#643]
I`m using django 2.2.6

Model_name.tags.add("smthng") return arror cause method "get_query_set()" in taggit/managers.py/_TaggableManger named like "get_queryset()"

**Comment by jdufresne** [comment]
Django normalized all methods to `get_queryset()` in commit https://github.com/django/django/commit/6983a1a540a6e6c3bd941fa15ddd8cb49f9ec74e (Mar 8, 2013)
