### ISSUE TITLE
tag cloud not working on Django version 3

### ISSUE THREAD

**Issue by pythonbest** [jazzband/django-taggit#661]
It's probably because django-classy-tags has old codes.
However django-classy-tags is likely no more maintained.

What can i do for tag cloud function on Django 3 ?
Or, can djago-taggit package solve this problem ?

**Comment by ghostforpy** [comment]
pip install six
change:
in managers.py, forms.py, utils.py ("from django.utils import six" > "import six")
in models.py ("from django.utils.encoding import python_2_unicode_compatible" > "from six import python_2_unicode_compatible")

"./manage.py makemigrations XXX" is work

**Comment by pythonbest** [comment]
Thank you, ghostforpy. However I dont accept your answer because it requires to modify library code.
I want to use django-taggit without modifying library code.
I studied the logic of tag cloud, and django-taggit depends on django-taggit-templatetags2 and django-taggit-templatetags2 depends on django-classy-tags.
I think one of these libraries need to be modified for tag cloud when used with Django 3.0.

**Comment by pythonbest** [comment]
Good news. Today I tested tag cloud in Django 3.0 and works well. Probably django-classy-tags upgraded to be compatible with Django 3.0.

**Comment by Pryla** [comment]
> I tested tag cloud in Django 3.0 and works well.

@pythonbest could you share which library you used exactly to make it work? I cannot find anything these days that would work. Tag-Clouds seem so outdated but I still would like to create one.

Cheers

**Comment by pythonbest** [comment]
Hi, Pryla.
I tested on following.
- django-taggit (v1.1.0)
- django--taggit-templatetags2 (v1.6.1)
- django-classy-tags (v1.0.0)
Cheers.

2021년 6월 16일 (수) 오전 6:20, Pryla ***@***.***>님이 작성:
