### ISSUE TITLE
ModuleNotFoundError: No module named 'taggit'

### ISSUE THREAD

**Issue by rajvijay68** [jazzband/django-taggit#669]
Python 3.7
Django 3.0.3

ran `pip install django-taggit`

Installed successfully

Added 'taggit' to `INSTALLED_APPS` in `settings.py`

Still getting the error 

`ModuleNotFoundError: No module named 'taggit'`

**Comment by dpthegrey** [comment]
I am also having the same issue. I can see `django-taggit==1.2.0` on  `pip freeze`

**Comment by rajvijay68** [comment]
I am not sure where the issue was. I made sure vscode was using the virtual env's interpreter, but it still didn't work. Then I installed it globally, and it worked.

**Comment by dpthegrey** [comment]
I removed the python virtual environment and created a new miniconda environment and selected the interpreter from pyCharm IDE.  It's working now. :)

**Comment by rtpg** [comment]
Sounds like everything's good on both your ends? I'll close this for now, if anyone else comes across this issue please feel free to re-open and comment on this

**Comment by chanakyacal** [comment]
I am facing the same issue : ModuleNotFoundError: No module named 'taggit'. Followed the same process. in djago Using VScode. Pls. tell how to install globally.  I use docker and requirement.txt. While installing , it is  showing "installed successfully"

**Comment by rtpg** [comment]
@chanakyacal : when you do `python` to get a REPL, are you able to do `import taggit` on that line?

With IDEs it's very easy to not be pointing to the right environment for IDE checks. This is pretty complicated to explain in one PR comment, but try to make sure that you're installing into the right environment (virtual environment), and that your IDE is also looking at the right environment

**Comment by chanakyacal** [comment]
Python 3.8
using Docker 
[Followed following processes in sequence]

docker-compose run web pip install django-taggit

Installing collected packages: django-taggit
Successfully installed django-taggit-1.3.0

Added 'taggit' to INSTALLED_APPS in settings.py

[in models.py file , added following]
from taggit.managers import TaggableManager
tags = TaggableManager()

$ docker-compose run web python manage.py makemigrations  

ModuleNotFoundError: No module named 'taggit'

Need solution, tried installing with pipenv, pip but of same error



RUN pip install -r requirements.txt
- (requirments.txt file contains (Django>3.0 , django-taggit , psycopg2 >=2.7))
on Docker-compose up 
Installed successfully



Still getting the error

ModuleNotFoundError: No module named 'taggit'

**Comment by rtpg** [comment]
Would you be able to post the full stack trace for `ModuleNotFoundError`? this might have information that is helpful in figuring out what is going on here. 

I am not very knowledgeable on how `docker-compose` works or how it persists modules, my understanding of just `docker` is that you would actually want to run `pip install django-taggit` when building the image, not as that `run` command before, because filesystem changes wouldn't be persisted between container runs. 

So in your case you will likely want to put `pip install django-taggit` into your `Dockerfile`, not do it as a `run` command.
