### ISSUE TITLE
Django-Taggit & Django-Filter causes AssertionError: resolved field 'tags' with 'exact' lookup to an unrecognized field type TaggableManager

### ISSUE THREAD

**Issue by alnikolaj** [jazzband/django-taggit#671]
Hello Everybody, 

I wish to use Django-Filter together with Django-Taggit, unfortunately, it causes a problem: 

> AssertionError: PostFilter resolved field 'tags' with 'exact' lookup to an unrecognized field type TaggableManager. Try adding an override to 'Meta.filter_overrides'. See: https://django-filter.readthedocs.io/en/master/ref/filterset.html#customise-filter-generation-with-filter-overrides

Here is my code: 

#models.py

```
from taggit.managers import TaggableManager
    class Post(models.Model):
        title    = models.CharField(max_length = 200)
        text     = models.TextField(null = True, blank = True)
        tags     = TaggableManager()
        
        def __str__(self):
            return self.title
```

#forms.py

```
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
```

#filter.py

```
class PostFilter(django_filters.FilterSet):
    class Meta:
        model = Post
        fields = ['title', 'text']
```

#views.py

```
def index(request):
    posts = Post.objects.all()
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    context = {'posts':posts, 'myFilter':myFilter}
    return render(request, 'posts/index.html', context)
```

If I write "exclude = ['tags']" in filter.py the problem goes away, sure - but that defeats the purpose since I would like to be able to filter by tags. Is that possible with django-filter? 

Thanks in advance!

**Comment by rtpg** [comment]
I think here the problem is you don't have builtin support for tags with `django-filter`. However, if you go to that link you'll find that you could specify a filter for like (spitballing here but I think it would work):

```
class PostFilter(django_filters.FilterSet):
    class Meta:
        model = Post
        fields = ['title', 'text', 'tags']
        filter_overrides = {
             TagField: { # TODO you'll need to look up the exact model field
                 'filter_class': django_filters.CharFilter,
                 'extra': lambda f: {
                     'lookup_expr': 'name__icontains', # here we're saying to look through the icontains prop on name
                 },
             },
             
         }
```
