### ISSUE TITLE
tag_kwargs causing errors

### ISSUE THREAD

**Issue by rgs258** [jazzband/django-taggit#675]
version 1.3.0  which adds an unnamed argument, tag_kwargs, to the signature of _to_tag_model_instances within taggit.managers._TaggableManager. I don't think this is broken in djangp-taggit specifically, but packages that I am using that require version >=1.0,<2.0 are taking 1.3.0 and this api change is breaking them. I will lock in 1.2.0 for the time being. I just wanted to mention this. Feel free to close this as won't fix.

**Comment by rgs258** [comment]
specific error message is `_to_tag_model_instances() missing 1 required positional argument: 'tag_kwargs'`

**Comment by nkuttler** [comment]
I see the same problem ```modelcluster/contrib/taggit.py", line 44, in add
    tag_objs = self._to_tag_model_instances(tags)```
This makes it look like a wagtail/modelcluster problem as the method is supposedly private, I will report it there.

**Comment by rgs258** [comment]
Note https://github.com/wagtail/wagtail/pull/6063

**Comment by gasman** [comment]
Can confirm that django-taggit is not at fault here - the django-modelcluster package used by Wagtail is patching the `_to_tag_model_instances` method.

This is now fixed in https://github.com/wagtail/django-modelcluster/pull/123 and released in django-modelcluster 5.0.2.

**Comment by rtpg** [comment]
OK in any case it looks like we should generate a migration to stabilize stuff. `_to_tag_model_instances` is meant as a private API IIRC, but I think at least we should be generating a migration to clear up that style of error. Thanks for the detailed reports here

**Comment by rtpg** [comment]
Alright, the damage has mostly been done here and seemingly is fixed, but we definitely could have been more careful here (at least providing a default).  I don't feel like there's much value in trying to revert this, but for any future changes we'll try to include defaults when approrpriate
