### ISSUE TITLE
When I use UUID for primary key , it will cause overflow error, Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by KyleQiLiu** [jazzband/django-taggit#679]
In one of my model objects, I use UUID for PK. 
When I want to get all the tags belong to each object, it will cause this overflow error.

I can print out all the tags in Tag model, but I can not get the tags in each Model object.
Then I change back to Django's default pk, tags work again.

I assume that's the UUID cause this problem, any thoughts about this problem?
Thank you.

**Comment by syk1k** [comment]
A common use case of a non-integer primary key, is UUID primary key. django-taggit provides a base class GenericUUIDTaggedItemBase ready to use with models using an UUID primary key:
```python
from django.db import models
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase

class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

class Food(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # ... fields here

    tags = TaggableManager(through=UUIDTaggedItem)
```

**Comment by syk1k** [comment]
This should work for you

**Comment by jbfriedrich** [comment]
@syk1k Could you explain a little bit why this is necessary? I just ran into the same problem, was using UUID for an ID, then used your example above, but have difficulties understanding why it is necessary. I am new to Django and would love to gain a better understanding of whats happening here.

**Comment by syk1k** [comment]
@jbfriedrich This is because, by default django-taggit assume that models's Ids are integers.
If you want to UUID you need to let the Tag manager to know that your Ids are not Integers but UUID.
I don't if this is enough

**Comment by jbfriedrich** [comment]
Thanks @syk1k. Yes, that part I understand, I do not understand though why it is necessary to create the `UUIDTaggedItem` class and reference that in the TaggableManager: 

```
class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
```

I guess I need to go through the code of TaggableManager and try to understand how that works in detail. Thank you!

**Comment by syk1k** [comment]
Because it's the only way Tags will be created for you with UUID.
Just go through the docs and try to check the code maybe it will help.
You're welcome

**Comment by rtpg** [comment]
@jbfriedrich basically the way that tags work by default is through an "integer id, content type" pair of data (since by default primary keys are integers). UUIDs require more space in general, so you need to override the through table to instead use "uuid id, content type" pairs, so that your DB has space to save the ID.

[this article on generic foreign keys](https://micropyramid.com/blog/understanding-genericforeignkey-in-django/) (the default backing for linking tags) might help you out here.
