### ISSUE TITLE
Q() Lookup AND Condition Returns No Results

### ISSUE THREAD

**Issue by jaradc** [jazzband/django-taggit#680]
# My Question

How do I filter posts by user containing multiple tags using **AND** conditional logic and Django's `Q()` complex lookups?

### What Am I Trying To Do?
If someone visits a URL like so: `http://127.0.0.1:8000/username/posts/tagged/django+python/`, my URL pattern grabs the last part ("django+python"), splits it by the `+` sign, and I want to filter my posts model by these two tags where they contain both `django` AND `python`.

### What I Expect To Work?
Currently, I see two posts in my database that have both "django" and "python" tags:

```
u = User.objects.get(username=myusername)
for post in Post.objects.filter(tags__slug='django', user=u).filter(tags__slug='python'):
...     print(post.tags.all())
...     
<QuerySet [<Tag: python>, <Tag: django>, <Tag: templates>, <Tag: html>, <Tag: stylesheet>, <Tag: css>]>
<QuerySet [<Tag: python>, <Tag: django>, <Tag: jquery>]>
```

When I use Q() complex lookup logic, I get no results, and that's my question --> Why?

Here my multiple attempts.

#### Attempt 1
```
>>> from operator import and_
>>> from functools import reduce
>>> from django.db.models import Q
>>> slugs = ['python', 'django']
>>> conditions = [Q(tags__slug=slug) for slug in slugs]
>>> query = reduce(and_, conditions, Q())
>>> u.post_set.filter(query)
<QuerySet []>
```

#### Attempt 2
```
>>> u.post_set.filter(Q(tags__slug='python') & Q(tags__slug='django'))
<QuerySet []>
>>> u.post_set.filter(Q(tags__slug='python'), Q(tags__slug='django'))
<QuerySet []>
```

#### Attempt 3
```
>>> u.post_set.filter(Q(tags__slug__exact='python') & Q(tags__slug__exact='django'))
<QuerySet []>
```

### models.py
```
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ...
    tags = TaggableManager()
```

![django-taggit-table](https://user-images.githubusercontent.com/12854767/87844565-093cdf80-c873-11ea-8a6d-22b8e234b7d4.png)

### urls.py
```
urlpatterns = [
    path('posts/tagged/<tags>/', TagListView.as_view(), name='posts_tagged'),
]
```

#### Why don't I just chain filters and call it a day?

Because I want the user to be able to filter posts by a theoretically unlimited number of tags.
Ex: `http://127.0.0.1:8000/username/posts/tagged/django+python+jquery+css+javascript+some-tag+whatever/`,
Point is, there is no discrete number of tag slots available, it should be free-range for flexibility for the user.

**Comment by rtpg** [comment]
Let's look at the following query:
```python
>>> print(Document.objects.filter(Q(tags__name="foo")&Q(tags__name="bar")).query)
SELECT "docs_document"."id", "docs_document"."name" 
FROM "docs_document" INNER JOIN "docs_uuidtaggeditem" ON ("docs_document"."id" = "docs_uuidtaggeditem"."content_object_id") INNER JOIN "docs_mycustomtag"
 ON ("docs_uuidtaggeditem"."tag_id" = "docs_mycustomtag"."id") WHERE
 ("docs_mycustomtag"."name" = foo AND "docs_mycustomtag"."name" = bar)
```

When we do these sorts of ORM lookups through a relation, we create one result per (object, tag) pair, right? But the filters work on each row. So we're looking for an (object, tag) pair where the  `name` equals one result and another at the same time. Suffice to say, this will basically always be empty, right? Like no tag will have the name `django` and `python` at the same time.

I'm not sure it's the best recommendation, but my recommendation would be for you to directly query the through table here. 

This is a bit of a tricky problem, though! Imagine doing this by hand. You could look at every object's tags (so one query per post to get tags), and that would be the easiest to code (but not super performant, right). But instead you could filter down to everything that has at least one of these tags, and then filter through that (though you're still going to need to do some math).

```python
# get all the Post <-> tag associations that cover at least one tag
relevant_items = Post.tags.through.objects.filter(
   name__in=['django', 'python'], 
   # only give me tags for Posts
   content_object_type=ContentType.objects.for_model(Post)
)
# at this point we can easily get all the posts that have _either_ django or python. But we want to know those that have both! 
# If both tags are present, then the post will be present twice in relevant_items
# (here there are two terms so we only filter for 2, if there were 10 items you filter for 10, etc)
items_with_all_tags = relevant_items.annotate(count=Count('content_object_id')).filter(count=2)
posts = Post.objects.filter(id__in=items_with_all_tags.values_list("id", flat=True)
```

bit of a mouthful but this will work way better for your case.
