### ISSUE TITLE
Where should I put 'TAGGIT_CASE_INSENSITIVE'

### ISSUE THREAD

**Issue by ruslaniv** [jazzband/django-taggit#684]
The documentation says:

> If you want django-taggit to be CASE-INSENSITIVE when looking up existing tags, you’ll have to set the TAGGIT_CASE_INSENSITIVE setting to True 

It says nothing about where this line should go.
Where should I put this line? In `settings.py` or in `models.py`?

**Comment by AdamDonna** [comment]
Based on the tests it looks like it should be in the settings. https://github.com/jazzband/django-taggit/blob/b21c94be8b6b2da9516ee1f635d87f1323a88a43/tests/tests.py#L723

I think some clearer docs would help clear this up for other users.

**Comment by bandirom** [comment]
According to _TaggableManager on 211 line

`python
case_insensitive = getattr(settings, "TAGGIT_CASE_INSENSITIVE", False)
`
we need to add this parameter in settings.py

**Comment by rtpg** [comment]
Yep, this is currently a global setting (tho personally I think it would make sense for this to be overridable on tag-based basis, depending on your use-case)

**Comment by rtpg** [comment]
(keeping this open for now, will close when we tweak the documentation)

**Comment by AdamDonna** [comment]
@rtpg Did you want me to update the docs? Is there an issue or card i should pick up?

**Comment by rtpg** [comment]
Yeah if you could send in a PR that makes the originally cited text a bit clearer we can merge that in, and close out this issue

**Comment by AdamDonna** [comment]
This is in the getting started docs. I suspect we can close this without any modifications. 
See https://github.com/jazzband/django-taggit/blob/master/docs/getting_started.rst#getting-started

**Comment by rtpg** [comment]
alright just modified that sentence, closing this one out now
