### ISSUE TITLE
TaggableManager.set() API does not match RelatedManager.set()

### ISSUE THREAD

**Issue by rjmackay** [jazzband/django-taggit#686]
TaggableManager has `set(*tags, clear=False)` while RelatedManager expects the tag objects as a list ie `set(tags, bulk=True, clear=False, through_defaults=None)`.
Would it be possible to support setting tags as a list/tuple too? The different interface makes it harder to plug that TaggableManager into other django libraries.

**Comment by auvipy** [comment]
feel free to dig in and start a WIP PR to improve it?

**Comment by rtpg** [comment]
I'm tempted to qualify this as a bug, due to not following SOLID. Thanks for pointing this out. A simple base case here would be to take params, but throw a `NotImplementedError` on stuff we don't support.

**Comment by coredumperror** [comment]
I agree 100% that this is a bug. I've now been burned by this difference in APIs between `TaggableManager.set()` and `RelatedManager.set()`, as I'm trying to use the same code to set various different types of tags on objects, and only one of those types is handled by django-taggit. So the API being different screws me.

**Comment by rtpg** [comment]
@coredumperror feel free to send in a PR, I'll gladly review it to get it in. I think when I made the original comment I didn't see a straightforward way of getting it to work

**Comment by pablolmedorado** [comment]
I've been facing this issue trying to use a tags field together with the library "[django-import-export](https://github.com/django-import-export/django-import-export)". It's been impossible.
