### ISSUE TITLE
Get count of object by each tag

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-taggit#689]
I have the following model structure
```
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager


class Product(models.Model):
    data = models.CharField(max_length=200)

class ProductRelation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    tag = TaggableManager()

class TrackingData(models.Model):
    d = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
```

For example, I have the following tags associated with the product
```
tag1, tag2, tag3
```

I want to get the count of `TrackingData` by each tag. So the expected output is
```
tag1            4
tag2           2
tag3           5
```

**How can I get the count of objects associated with the each tag?**

**Comment by nightwolfgroup** [comment]
You could pull it when you render your view.
Make sure you import Count (from django.db.models import Count)

tags = ProductRelation.tag.all().annotate(Count('product'))

**Comment by rtpg** [comment]
This looks answered to me, closing
