### ISSUE TITLE
Tags associated with a color

### ISSUE THREAD

**Issue by MatejMijoski** [jazzband/django-taggit#690]
I want to have tags associated with a color by a user. Is this possible using Taggit and if so, is there a snippet somewhere that would enable this?

**Comment by velis74** [comment]
https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#custom-tag

**Comment by rtpg** [comment]
yep, you'll want to create a custom tag with colors (and if you want to have that be per-user, you'll need to set up a thing for that as well)
