### ISSUE TITLE
Rendering tags in template with Bootstrap-tagsinput

### ISSUE THREAD

**Issue by GBrachetta** [jazzband/django-taggit#702]
I'm trying to make your great app work but I have the following problem:

I'm using [bootstrap-tagsinput](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput) to render tags so:

![Screenshot 2020-11-23 at 00 02 25](https://user-images.githubusercontent.com/57924268/99919705-46cce000-2d1f-11eb-8021-4859756bd9d8.png)

But when I access my edit view, pre-populating the form, I get:

![Screenshot 2020-11-23 at 00 04 41](https://user-images.githubusercontent.com/57924268/99919742-91e6f300-2d1f-11eb-8d6c-689fee6de4ff.png)

My form is:

```python
class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = (
            ...
            "tags",
        )
        widgets = {"tags": forms.TextInput(attrs={"data-role": "tagsinput"})}
```

(I need to have the data-role for the plugin to work, and I use CrispyForms)
How can I solve this issue and get the right values when I need to access the form to edit it?

**Comment by rtpg** [comment]
@GBrachetta sorry for the long wait here (and you mght have already found the answer) but for your widget you'll want to use `taggit.forms.TagWidget`, not just the raw `TextInput`. Why? Because `TagWidget` has a mixin that handles rendering the tag out properly. I believe that should fix your issue
