### ISSUE TITLE
Django Form Admin and Taggit Through Model

### ISSUE THREAD

**Issue by skagrawal10** [jazzband/django-taggit#705]
Hi, 

I am using Taggit library. I need to use some additional fields like featured_tag and hence I created a through model. Now, I need to modify Django Admin for the same. So, on front end, I have used VueJs to create assign which tag is featured, but, how we would handle in BackEnd form while saving. As I understand, we need to call save_m2m() function, but how we will pass these addtional attributes. Any thoughts ?

**Comment by rtpg** [comment]
Dupe of #706
