### ISSUE TITLE
Serializers for django-taggit

### ISSUE THREAD

**Issue by kasteph** [jazzband/django-taggit#707]
The django-taggit-serializers project appears to be unmaintained for a few years now (see https://github.com/glemmaPaul/django-taggit-serializer/issues/44). Per @jezdez's suggestion in https://github.com/jazzband-roadies/help/issues/91#issuecomment-766396493, I would like to propose adding serializers to the django-taggit project as a feature.

**Comment by auvipy** [comment]
> The django-taggit-serializers project appears to be unmaintained for a few years now (see [glemmaPaul/django-taggit-serializer#44](https://github.com/glemmaPaul/django-taggit-serializer/issues/44)). Per @jezdez's suggestion in [jazzband-roadies/help#91 (comment)](https://github.com/jazzband-roadies/help/issues/91#issuecomment-766396493), I would like to propose adding serializers to the django-taggit project as a feature.

please proceed

**Comment by rtpg** [comment]
I've reached out to Paul on this topic, waiting for a reply

**Comment by ysomad** [comment]
Any updates?

**Comment by rtpg** [comment]
I got no reply from Paul on this one.

I just compared the licenses, and everything seems in order for vendoring this in. The licenses are identical except for copyright and COPYRIGHT OWNER vs COPYRIGHT HOLDER. 

I'll vendor this in as a different namespace to make stuff easier to integrate for people though.

**Comment by rtpg** [comment]
Alright this is vendored in and part of the 1.5.0 release

**Comment by glemmaPaul** [comment]
Looks like it is vendored in, amazing!

**Comment by glemmaPaul** [comment]
I will get in the repo readme that it is no longer maintained, and can be used directly from django-taggit. 

Thank you guys for such amazing work :)

**Comment by rtpg** [comment]
@glemmaPaul thank you for the initial work! I do hope that the vendoring is to your liking

**Comment by glemmaPaul** [comment]
@rtpg No it looks very good, thank you for pulling this in. Editing Readme now
