### ISSUE TITLE
ModuleNotFoundError: No module named 'taggit' from settings.py 

### ISSUE THREAD

**Issue by Boburshoh-oss** [jazzband/django-taggit#714]

**Comment by rtpg** [comment]
Are you sure you have the `django-taggit` package installed? For example, if you installed using `pip`, when you call `pip freeze`, does the package show up there?

There might be something else going on here as well, so if you post the full stacktrace someone might be able to help you out here

**Comment by rtpg** [comment]
closing until we get more information here
