### ISSUE TITLE
How to call taggit apis.

### ISSUE THREAD

**Issue by Tikam02** [jazzband/django-taggit#715]
How to post tags via post request using Django Rest Framework

**Comment by rtpg** [comment]
We don't have specific DRF support built-in, I would recommend writing a [custom relational field](https://www.django-rest-framework.org/api-guide/relations/#custom-relational-fields) to handle serialization/deserialization in whatever DRF serializer you are using. 

Ultimately APIs for tags are a bit tricky in how you want to handle X/Y/Z, so it's hard to offer an all-in-one solution for people.

**Comment by rtpg** [comment]
Another option you might have here is to use [django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer), it `might` provide what you want to have here.

**Comment by rtpg** [comment]
please feel free to ask more questions, for now I will close this

**Comment by PrynsTag** [comment]
[django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer) is said to be [deprecated](https://github.com/glemmaPaul/django-taggit-serializer/issues/54) and does not work with Django 4.0. The last commit is 2018.

Are there any beginner friendly solution you recommend?
