### ISSUE TITLE
blank=False not working on edit

### ISSUE THREAD

**Issue by francesco-filicetti** [jazzband/django-taggit#716]
Hi,
in my model class I have `tags = TaggableManager()` but when I edit new objects (from frontend/shell/API) blank/empty values are accepted.
Is it normal? How I can make it required?
This doesn't happen in backend or when I create new objects, where `tags` field is correctly validated.
Thank you

**Comment by rtpg** [comment]
This is a classic Django problem, where [`full_clean` is not called by Django stuff in general](https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.full_clean). It _is_ called by `ModelForm`s! But that's it.

What I have seen in many places is to do something like the following in your model class:

```python
class MyModel(Model):
   ...
   def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
```

This is hacky, but _will_ at least prevent you from saving stuff without tags. 

That being said, there might be a way for taggit to provide validation for common usage (I imagine you're using Django Rest Framework?) in general....
