### ISSUE TITLE
conflict in migrations

### ISSUE THREAD

**Issue by HassanKadhem** [jazzband/django-taggit#722]
I have faced a weird issue with django-taggit in one of my projects. When I created my app's migrations which depend on taggit the generated file had this taggit migration `0004_auto_20210415_1403` in the dependencies list. However, when I wanted to deploy my application using dokku I was surprised that the most recent migration of taggit is `0003_taggeditem_add_unique_index` hence migrate command always failed because 0004 migration is missing. 

Now I don't understand why this is happening but both versions of taggit on my local machine and the server are the same, that is 1.3.0

However the python version is different, my machine's python version is 3.9 and the server's is 3.6. I don't think that should be a problem either. 

Is there a good explanation for this?

**Comment by rtpg** [comment]
@HassanKadhem this sounds like what is happening is that at one point in local development you end up having a migration generated. Would you be able to post the contents of `0004_auto_20210415_1403.py` here (and include what version of Django you are using)? 

This feels like an issue with `django-taggit` and migrations, and we need to be fixing up our migrations somehow.

**Comment by HassanKadhem** [comment]
@rtpg 

looking at the migration file I think we have a lead. This is the content of the migration file 

```
# Generated by Django 3.2 on 2021-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

I'm running django 3.2

It is clear that the migration got created when I ran `makemigrations` locally but why?, and why is it not being generated on the server although the same django version and app settings are there.

**Comment by rtpg** [comment]
OK I believe this is related to a new Django feature (shipped in 3.2) that lets you customize the primary key shape when it's not explicitly set in the models. 

Have you set the [DEFAULT_AUTO_FIELD](https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field) setting in your project? I believe that this problem goes away if you don't set it/if you set it to `AutoField`. This is probably not what you want though!

Thanks for flagging this though, this might be a bit of a tricky problem to solve in general for users

**Comment by HassanKadhem** [comment]
@rtpg 

you are right, except that the variable is set to `django.db.models.BigAutoField` out of the box when a new project is created. 
Even if this is fixed by rolling out a new `taggit` version with a migration, what will happen if the developer decides to switch back the auto field to the old one `AutoField` ? I think it will miss up everything, unless the field is deprecated

**Comment by rtpg** [comment]
One thing we can do is explicitly define the id field and use the AutoField definition (and tweak migrations to match that). Basically making explicit what Django 3.1 was doing implicitly. That will at least get the migration infra in the right state.

For the future, I think we'll need to do some fiddling around to let people set up the models correctly.

**Comment by HassanKadhem** [comment]
@rtpg But what If I really want to use `BigAutoField` ? I don't know but I feel like this is a django issue, it shouldn't be creating migrations on behalf of installed apps. I was thinking of reporting this as a bug in django but I'm not sure.

**Comment by rtpg** [comment]
It's not... really a bug in migrations per-se. Basically the original migration says "`id` is an `AutofField`". 

I do think it's a bit of a problem in general cuz this is totally not visible to people, but at the same time the migration tooling just completely ignoring an installed app (I think that Django doesn't by default know that `taggit.models` is a library and not your app) would be a bit odd. You would need to add some checks there...

Gonna think about this a bit overnight and try to post up some solution tomorrow

**Comment by rtpg** [comment]
@HassanKadhem It turns out that this issue has already been fixed [as of this commit](https://github.com/jazzband/django-taggit/blob/master/taggit/apps.py), but it's not in a release yet. The "fix" is to maintain the usage of `AutoField`. 

I agree that users should be able to use `BigAutoField` if they would like to for tags in principle, but I'm not 100% sure how we can do this for new users without making a mess for existing users in terms of migrations... but I will at least prep a release so you can get unblocked

**Comment by rtpg** [comment]
Alright version 1.4.0 was just put out on pypi. This should resolve your issue (technically release 1.3.0 didn't support Django 3.2 just yet...). I'm going to close this for now cuz I believe your core issue regarding migrations is resolved, though I still consider the `BigAutoField` thing a potential improvement. 

Please re-open this if upgrading to 1.4.0 doesn't resolve your issue!
