### ISSUE TITLE
Add example in the documentation about how to use a custom Tag model

### ISSUE THREAD

**Issue by gnotaras** [jazzband/django-taggit#73]
The current documentation has no info about the ItemBase.tag_model() method. If I wasn't guided to take a look look at the tests, I would have spent several hours trying to make this thing work. Please keep the documentation current and provide examples.

**Comment by rtpg** [comment]
There's now [a good chunk of documentation on using this](https://django-taggit.readthedocs.io/en/latest/custom_tagging.html?highlight=GenericTaggedItemBase#using-a-custom-tag-or-through-model). Things can always be improved of course
