### ISSUE TITLE
Copyright and license of the JazzBand logo

### ISSUE THREAD

**Issue by tijuca** [jazzband/django-taggit#734]
Hi,

while working on including the django-taggit documentation for Debian I noticed that the file jazzband.svg is getting side-loaded due the source of CONTRIBUTING.rst.

Debian is avoiding side loading by pointing such things to local files.

Modifying the relevant part so that a local copy of jazzband.svg is getting used is no technical problem. But I haven't found any information about the copyright and license for the brand graphics. Can you point me to some place where I can find this information, maybe I simply haven't found it yet. Or can you make a statement regarding these things?

Thanks!

**Comment by rtpg** [comment]
The canonical Jazzband logo is, I believe, sourced from the website ([github link to the directory here](https://github.com/jazzband/website/tree/main/jazzband/static/img)).

According to [that repo's readme](https://github.com/jazzband/website) we have:

> The content of this project is licensed under the Attribution-NonCommercial-ShareAlike 4.0 International license, and the underlying source code used to format and display that content is licensed under the MIT license.

I'm not sure about how this affects packaging for Debian, or what would be "ideal" in this case. Does that existing licensing work for your needs?

**Comment by tijuca** [comment]
Hi,

thanks! That's exact the peaces I missed. Thanks for pointing.

> I'm not sure about how this affects packaging for Debian, or what would be "ideal" in this case. Does that existing licensing work for your needs?

In Debian  we want to build every thing from source, but not only this, all the source must be compliant to the [DFSG](https://www.debian.org/social_contract#guidelines), means firstly all parts must be licensed under a license that is "[free enough](https://wiki.debian.org/DFSGLicenses)". And with your explanations from above I can point to the relevant parts were the logo was taken from and which license it is applying used. CC-BY-SA 4.0 is fine for the logo. No further need for doing anything on your side.
