### ISSUE TITLE
How to specify multiple tags in bulk_create

### ISSUE THREAD

**Issue by johnvonneumann7** [jazzband/django-taggit#739]
I would like to use `bulk_create` in the following configuration.
The `name` is set well, but the tags do not reflect anything, and there is no error, and I do not know the cause.
How can I specify multiple tags at the same time with bulk_create?

```python
models = []
for data in datas:
    model = Model(
        name=data['name'],
        tags=data["tags"].split(" "),
    )
    models.append(model)
Model.objects.bulk_create(models)
```

**Comment by rtpg** [comment]
For many-to-many relationships that require extra model creations, you have to do that manually on the side IIRC. [The docs](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-create) say that this doesn't work for many-to-many relationships by default

I think that [this SO question](https://stackoverflow.com/a/34093544/122757) shows a good way of doing it (basically you'll want to get the tag through model with `Model.tags.through`, and you'll need to do the tags lookup manually as well).

`bulk_create` returns the created objects so you can do something like:

```
models  = Model.objects.bulk_create(models) # you need the pk
tag_throughs = []
for datum, model in zip(data, models):
    for tag in datum["tags"].split(" "):
        tag_throughs.append(Model.tags.through(tag_id=..., object_id=model.pk))

Model.tags.through.objects.bulk_create(tag_throughs)
```

There's some stuff maybe wrong with my snippet, but that's the general jist

**Comment by afparsons** [comment]
Hi @rtpg, 

> tag_id=...,
Where do tag PKs come from? What if those tags do not exist yet?
