### ISSUE TITLE
TaggedItem has no field named 'content_object'

### ISSUE THREAD

**Issue by LarsAC** [jazzband/django-taggit#74]
In my model class I have a 

```
tags = TaggableManager(blank=True)
```

When I try to query 

```
photos = Photo.objects.filter(tags__name__in=[tag])
```

an error is displayed "TaggedItem has no field named 'content_object'".

This is with django-trunk r16299. Any ideas on this ?

Lars

**Comment by jdufresne** [comment]
Sounds like this issue has been resolved. Thanks.
