### ISSUE TITLE
TagField has_changed method returns True for empty strings

### ISSUE THREAD

**Issue by hemebond** [jazzband/django-taggit#749]
When trying to use a model with a tag field in an inlineformset, has_changed appears to always return True.

Django then thinks all the extra, empty forms in the formset have been changed and validation fails.

Seems to be the result of [calling clean()](https://github.com/jazzband/django-taggit/blob/master/taggit/forms.py#L41) and can be worked around by adding this after it:

```
        if data_value is None:
            data_value = []
```

otherwise the empty string will be compared to an empty list (`initial_value`).

**Comment by rtpg** [comment]
This is fixed in the latest release! Thank you for the report and the fix suggestion
