### ISSUE TITLE
similar_objects() Very slow.

### ISSUE THREAD

**Issue by johnvonneumann7** [jazzband/django-taggit#751]
We need to get it from among the related articles (200k) of a specific article, but
If there are a large number of objects, `similar_objects()` will take a long time to issue the query.

However, if there are a large number of objects, `similar_objects()` will take a long time to issue the query. So, I created my own method of retrieving the objects from the `django-taggit` source code as follows
The speed has improved considerably, but
Is there a more accurate way to get the related articles?

```python
tags = Model.objects.get(pk=pk).tags.all()
return (
    Model.objects.published()
    .annotate(n=models.Count("pk"))
    .exclude(pk=pk)
    .filter(tags__in=tags)
    .order_by("-n")
)
```

**Comment by rtpg** [comment]
No, I think this is a very good way of doing this! If this is not very performant, you should try doing `print(query.explain())`, and you should see what indices/etc are being used to process the query. 

The existing `similar_objects` tries to handle the multiple-model case and has to do a lot of weirdness to handle it. In cases where you are working off of a single model what you're doing is very good

**Comment by rtpg** [comment]
going to close this one for now, as a "duplicate" of #729, but having this snippet will be very helpful for people I think. Thank you!

**Comment by w-** [comment]
Thanks @johnvonneumann7 . Question to both you and @rtpg  about this part of the code:

`.annotate(n=models.Count("pk"))`

I think i'm misunderstanding what this is counting
To avoid confusion I'm going to refer to `Model` (capital M) as `MyModel`
To me this reads as counting the number of `MyModel` objects? wouldn't we want to count the number of tags to determine how similar something is?
