### ISSUE TITLE
Creating tags on bulk create

### ISSUE THREAD

**Issue by vishalpandeyvip** [jazzband/django-taggit#758]
Here is my code:
`
    build_data = [ContactDetail(**parse_content(df, i, social_site_lists), admin = request.user) for i in df.index ]
    ContactDetail.objects.bulk_create(objs = build_data,ignore_conflicts= True)
`

parse_content returns a dictionary, containing many fields, out of which one key is tags, which have a list of tags for that record. Is it possible to add these tags without using the object.tags.add([]), and creating all the records in a single database connection.

**Comment by isaac-nygaard-iteris** [comment]
What I implemented for bulk updates is:

- Fetch mapping from tag name to id, filtering on the `TagManager.all().model`. The `TagBase.save()` method is not really safe for bulk creation, so I go through and add each missing tag individually.
- Use `Through.bulk_create` for adding new tags, with `ignore_conflicts` enabled
- Use regular `Through.delete()` (apparently gets optimized to a single SQL query?) for bulk deletion

Seems to work fine

**Comment by Azmisov** [comment]
What I implemented for bulk updates is:

    Fetch mapping from tag name to id, filtering on the TagManager.all().model. The TagBase.save() method is not really safe for bulk creation, so I go through and add each missing tag individually.
    Use Through.bulk_create for adding new tags, with ignore_conflicts enabled
    Use regular Through.delete() (apparently gets optimized to a single SQL query?) for bulk deletion

Seems to work fine
