### ISSUE TITLE
List all available tags in the system

### ISSUE THREAD

**Issue by esseti** [jazzband/django-taggit#762]
Hello,
how can I retreive all the tags that are available in the current system?
i've various elements that have tags, i was looking for a function that gives me the set of all the tags that were used.

**Comment by rtpg** [comment]
If you are using just an out-of-the-box setup, your tags are storred in the `Tag` model (found in `taggit.models`). If this is a custom model (for example you have your own models derived from `ItemBase`), then you'll need to query that one instead.

 So if you are using the standard setup, ``Tag.objects.all()`` will give you the tags.
