### ISSUE TITLE
AUto-generated migration with Django 4.0

### ISSUE THREAD

**Issue by bmispelon** [jazzband/django-taggit#784]
Hi,

When using `taggit` with Django 4.0 and running `./manage.py makemigrations`, it generates a new migration file:
```
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
```

I believe this is caused by this: https://docs.djangoproject.com/en/4.0/releases/4.0/#migrations-autodetector-changes

Adding the migration to `taggit` doesn't seem to have negative side-effects. I've also tried adding this migration to taggit locally, reverting Django to 3.2, then running `makemigrations` again and it didn't detect any new changes.

It should be possible to prevent an issue like this from happening again by having `./manage.py makemigrations --check` run as part of your CI.

**Comment by auvipy** [comment]
thanks for report & suggesting. would you mind contributing to this?

**Comment by bmispelon** [comment]
> thanks for report & suggesting. would you mind contributing to this?

Sure thing. I thought writing a test would end up complicated but it was fairly straightforward using `call_command`.
I opened PR #785, let me know if I've missed anything.
