### ISSUE TITLE
Please make a Django 4.0 compatible release

### ISSUE THREAD

**Issue by gasman** [jazzband/django-taggit#786]
Apologies if this isn't the appropriate communication channel - I know as a maintainer that this sort of issue can be unwanted noise...

Please would you consider putting out a 2.1 release with the Django 4.0 compatibility fixes that are now in master? I'm really hoping that Wagtail 2.16 (due for release early February) will be able to offer formal Django 4.0 support, and currently django-taggit is the last remaining blocker for that.

Looking at issues / PRs here it's now been two weeks with no further compatibility issues reported, so I think we're confident as we'll ever be that a new release is good to go. Happy to assist if there's any way I can.

**Comment by rtpg** [comment]
@gasman that shouldn't be a problem, I understand the pain of waiting around for this kind of stuff. I'll see to prepping a release on Monday morning (JST), please reach out to me if this didn't happen by Tuesday

**Comment by gasman** [comment]
Thanks, much appreciated!

**Comment by rtpg** [comment]
@gasman release is now out, `2.1.0` on pypi, hope that resolves stuff for you
