### ISSUE TITLE
Taggit doesnt work in django 4.2

### ISSUE THREAD

**Issue by beliboba** [jazzband/django-taggit#820]
Taggit causes errors when launched with django 4.2.

**Comment by rtpg** [comment]
@beliboba could you please provide a stack trace or other information about the errors you are hitting?

**Comment by sahilrl** [comment]
django.db.utils.OperationalError: (1005, 'Can\'t create table `mydatabase`.`taggit_taggeditem` (errno: 150 "Foreign key constraint is incorrectly formed")')

**Comment by sahilrl** [comment]
``

**Comment by chambersh1129** [comment]
@beliboba do you mean Django 4.1?  That looks like the most recent version as of Aug 26 when you first commented.

I have a sample project using taggit and it worked as expected when running both Django 4.1 and the latest build 4.1.2.  Please confirm if you are still experiencing an issue and if so please provide a stack trace so we can investigate further.

**Comment by beliboba** [comment]
Sorry for not answering, working for me now

**Comment by chambersh1129** [comment]
@beliboba great to hear!  Closing issue.
