### ISSUE TITLE
Not compatible with Django 4.1

### ISSUE THREAD

**Issue by robdoesstuff** [jazzband/django-taggit#827]
This code: MyModel.objects.filter(tags__name__in=_tags)
works in Django 4.0 but breaks in 4.1 as:
django.core.exceptions.FieldError: Related Field got invalid lookup: name

**Comment by aliceni81** [comment]
I have the same issue.
When I do the filtering: **queryset.filter(tags__in=tag_ids)**, the error occurs saying
"django.db.utils.ProgrammingError: column articles_articlepage.tags does not exist"

django version: 4.1.2
python version: 3.10

**Comment by aliceni81** [comment]
@robdoesstuff I'm having the same issue and I am using Wagtail 4.0.4, django 4.1.2 and have the following code:

from modelcluster.contrib.taggit import ClusterTaggableManager
from taggit.models import TaggedItemBase


tags = ClusterTaggableManager(through='ArticlePageTag', blank=True)

class ArticlePageTag(TaggedItemBase):
    content_object = ParentalKey(ArticlePage, related_name='tag_list', on_delete=models.CASCADE)

According to my test, it seems that it's not the problem of django-taggit.

**Comment by aliceni81** [comment]
@robdoesstuff After I upgrade the django-taggit version from 2.1.0 to 3.0.0, this problem is solved. Please check your django-taggit version.

**Comment by robdoesstuff** [comment]
Ah yes you are correct. I was running 2.1.0 and the problem does not exist under 3.0.0. Thank you
