### ISSUE TITLE
`TagListSerializerField` is not a `ListSerializer`

### ISSUE THREAD

**Issue by janrito** [jazzband/django-taggit#828]
drf-spectacular fails to understand that the field should be serialised into a list of strings, rather than a string.

@ollie-zhang submitted the issue to the the original [repo](https://github.com/glemmaPaul/django-taggit-serializer/) here https://github.com/glemmaPaul/django-taggit-serializer/issues/47

I botched a fix 

```
from drf_spectacular.extensions import OpenApiSerializerFieldExtension
from drf_spectacular.openapi import AutoSchema
from drf_spectacular.plumbing import build_array_type, build_basic_type  # type: ignore
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import Direction


class TagListSerializerFieldFix(OpenApiSerializerFieldExtension):
    target_class = "taggit.serializers.TagListSerializerField"

    def map_serializer_field(self, auto_schema: AutoSchema, direction: Direction):

        return build_array_type(build_basic_type(OpenApiTypes.STR))  # type: ignore
```

But it would be nice if it was not needed

**Comment by rtpg** [comment]
Thank you for reporting this! Definitely sounds better if we use a `ListField` given... well.. it's a tag list! Thank you for posting the workaround as well.
