### ISSUE TITLE
Django 4.1 support

### ISSUE THREAD

**Issue by dustinblanchard** [jazzband/django-taggit#830]
Taggit is the last dependency blocking our update to Django 4.1. I see you have support merged into the main branch now, are there plans to release this soon?

**Comment by rtpg** [comment]
@dustinblanchard sorry for getting back at this.

First things first, the Django 4.1 release did not require code changes, so 3.0.0 should work with 4.1 out of the box (unless you're a stickler for PyPI classifiers). You can also do a pip install of what's on `main` ([see this](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)) by pointing to a specific commit. I try to make sure `main` is always "releasable", but don't push out releases until we have real code changes.

If you want the release, we should have one in the coming days though.
