### ISSUE TITLE
_get_extra_restriction - How Necessary is it?

### ISSUE THREAD

**Issue by jaradc** [jazzband/django-taggit#841]
I have a question about this code in `managers.py`:

```
    def _get_extra_restriction(self, alias, related_alias):
        extra_col = self.through._meta.get_field("content_type").column
        content_type_ids = [
            ContentType.objects.get_for_model(subclass).pk
            for subclass in _get_subclasses(self.model)
        ]
        return ExtraJoinRestriction(related_alias, extra_col, content_type_ids)

    def _get_extra_restriction_legacy(self, where_class, alias, related_alias):
        # this is a shim to maintain compatibility with django < 4.0
        return self._get_extra_restriction(alias, related_alias)

    # this is required to handle a change in Django 4.0
    # https://docs.djangoproject.com/en/4.0/releases/4.0/#miscellaneous
    # the signature of the (private) funtion was changed
    if django.VERSION < (4, 0):
        get_extra_restriction = _get_extra_restriction_legacy
    else:
        get_extra_restriction = _get_extra_restriction
```

If I understand correctly, the whole point of this code is to add an additional `INNER JOIN` restriction with IDs of content types.

```
SELECT "categories_tag"."name",
       COUNT("categories_tag"."name") AS "count"
  FROM "categories_tag"
 INNER JOIN "categories_taggeditem"
    ON ("categories_tag"."id" = "categories_taggeditem"."tag_id")
 INNER JOIN "content_content"
    ON ("categories_taggeditem"."object_id" = "content_content"."id" AND ("categories_taggeditem"."content_type_id" IN (10,11,14,12,24,29,30,28,34,33)))
 WHERE "content_content"."user_id" = 1
 GROUP BY "categories_tag"."id"
 ORDER BY "count" DESC
```

The problem is, this part:

```
content_type_ids = [
    ContentType.objects.get_for_model(subclass).pk
    for subclass in _get_subclasses(self.model)
]
```

is causing an SQL query each time it gets a subclass. I am noticing this when using Django Debug Toolbar.

My question is, how necessary is this extra join restriction if it comes at the cost of extra queries? Does this happen only once and get cached somewhere? Is it possible to do without this extra restriction with little danger?

Here's a picture for fun.

![django-content-type-taggit-similar-queries](https://user-images.githubusercontent.com/12854767/212425606-607231ac-53f1-4b68-be2a-85efc85c5ffc.jpg)

**Comment by rtpg** [comment]
from Django's implementation for `get_for_model`:
```
    def get_for_model(self, model, for_concrete_model=True):
        """
        Return the ContentType object for a given model, creating the
        ContentType if necessary. Lookups are cached so that subsequent lookups
        for the same model don't hit the database.
        """
        opts = self._get_opts(model, for_concrete_model)
        try:
            return self._get_from_cache(opts)
        except KeyError:
            pass

```

yep this stuff is cached, and _should_ not hit weird perf issues in situations where you are not using cache.

What's actually happening is actually happening of course (do you have caching disabled entirely in your development environment? Bit of a common thing), but this "should" be free. 

In a production environment you will of course make the query, but the query result will be cached per model and so on the second or third or fourth request it will end up being zero requests (that's the idea ofc).
