### ISSUE TITLE
Failing tests:  Update tox, gh workflows so tests run successfully.

### ISSUE THREAD

**Issue by imAsparky** [jazzband/django-taggit#846]
G'day folks,

While working on my version of django-taggit to learn more about Django, taggit, and test some ideas I have found a few items that can help the failing tests.  The items below have made all my tests work ok.

GitHub workflow.
* Add a workaround for tests to pass, see issue https://github.com/actions/setup-python/issues/544.  Users have pinned to ubuntu20.04 until a solution is found.
* Update actions/checkout@v2 to actions/checkout@v3 to silence deprecation warnings.

Django tox test matrix.
* dj-main has minimum py3.10.

I'm working on a PR and it should come through a bit later.

cheers

**Comment by rtpg** [comment]
Thanks for this report! I included your changes in other changes the other day
