### ISSUE TITLE
Getting this error while running tests: 'index_together' is deprecated. Use 'Meta.indexes' in 'taggit.TaggedItem' instead.

### ISSUE THREAD

**Issue by mister-rao** [jazzband/django-taggit#867]
Getting this error while running tests:

```
django.utils.deprecation.RemovedInDjango51Warning: 'index_together' is deprecated. Use 'Meta.indexes' in 'taggit.TaggedItem' instead. 
``` 

Versions:
Django = "4.2.5"
django-taggit = "4.0.0"

**Comment by paolodina** [comment]
1. it's a warning, not an error (you can ignore it)
2. [ref.](https://docs.djangoproject.com/en/4.2/releases/4.2/#index-together-option-is-deprecated-in-favor-of-indexes) Django 4.2 release
3. https://github.com/jazzband/django-taggit/pull/862

**Comment by mister-rao** [comment]
This prevents me from running tests

**Comment by rtpg** [comment]
Django 5.0 has not had an official release yet, so we do not support Django 5.0 yet.

Having said that, @mister-rao you should look into `warnings.filterwarnings` [here](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings). It provides the way you can set up your code to ignore the warning. I stick this kind of stuff in my `settings.py`. The warning is fine to ignore.

**Comment by rtpg** [comment]
Closing this now with "please use `warnings.filterwarnings`". A future release will remove the deprecated code (likely in conjunction with a release adding Django 5.0 support).
