### ISSUE TITLE
Double quotes in tag name

### ISSUE THREAD

**Issue by mjtamlyn** [jazzband/django-taggit#87]
Whilst the fix in #23 does fix commas in tag names, I have need of double quotes in tag names (again a predefined set of tags), which is currently not possible. Would be nice to be able to escape them somehow.

**Comment by rtpg** [comment]
You can add your own custom tag parser now to resolve this kind of issue (at least as a workaround if you have "weird" data). It's possible the base stuff doesn't even have this problem anymore. In any case, closing it out for now
