### ISSUE TITLE
TagWidget.render assumes value is queryset

### ISSUE THREAD

**Issue by tedtieken** [jazzband/django-taggit#90]
For a complicated set of reasons, I intercept and modify the tags on my object before rendering the form.  Some of them get displayed in their own true-false fields, others get displayed as tags.

To do this, in my form's **init** method I do some work on the tags, then reset the initial values of the tag field to a list of tags.

However, the TagWidget.render method assumes it is getting a queryset, not a list.  As lists have no attribute select_related, this fails.

To fix I have changed the TagWidget.render method as such:

```
class TagWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        from django.db.models.query import QuerySet
        if type(value) == QuerySet:
            value = value.select_related("tag")        
        if value is not None and not isinstance(value, basestring):
            value = edit_string_for_tags([o.tag for o in value])
        return super(TagWidget, self).render(name, value, attrs)
```

I'm not sure how common it is to want to pre-filter the tags.

**Comment by mevinbabuc** [comment]
How come this is not still merged into the master ? It's been a couple of years and its still an issue.

**Comment by jdufresne** [comment]
Thanks for the bug report. Would you like to contribute this fix as a PR with an included test?

**Comment by rtpg** [comment]
Given that `TagWidget` no longer renders itself, I don't believe this to be an issue (or at least not one in `django-taggit`) anymore
