### ISSUE TITLE
TemplateDoesNotExist admin/taggit/merge_tags_form.html

### ISSUE THREAD

**Issue by rafammpp** [jazzband/django-taggit#920]
When following the documentation about [merging tags in the admin](https://django-taggit.readthedocs.io/en/latest/admin.html#merging-tags-in-the-admin), It throws a TemplateDoesNotExist error when you try to execute the admin action "Merge selected Tags".

The folder "templates" is missing inside the pypi release package. Installing from git doesn't solve the issue.

**Comment by rtpg** [comment]
This should be fixed in 6.1.0 (at least on my end confirmed that the html files are now properly included). Thanks for reporting this!
