### ISSUE TITLE
django.db.utils.OperationalError: no such column: "taggit_taggeditem" on fresh Django install

### ISSUE THREAD

**Issue by mfoacs** [jazzband/django-taggit#926]
Tried with Django 4.2, 5.0 and 5.1.2. Python 3.11.

Steps to reproduce:
1. pip install django-taggit
2. add "taggit" to the installed apps
3. pyhton manage.py migrate

`Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
  Applying taggit.0004_alter_taggeditem_content_type_alter_taggeditem_tag... OK
  Applying taggit.0005_auto_20220424_2025... OK
  Applying taggit.0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx...Traceback (most recent call last):
  File "/usr/home/freebsd/wt/lib/python3.11/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/freebsd/wt/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 350, in execute
    return super().execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: "taggit_taggeditem" - should this be a string literal in single-quotes?

django.db.utils.OperationalError: no such column: "taggit_taggeditem" - should this be a string literal in single-quotes?`

Google has not much to offer.

Thanks for your help!

**Comment by mfoacs** [comment]
It turns out it's a sqlite3 issue. Please ignore, sorry for the noise!

**Comment by mfoacs** [comment]
It turns out it's a sqlite3 issue. Please ignore, sorry for the noise!

**Comment by jonathanmorgan** [comment]
What was the resolution? This still happens in python 3.11, not in 3.9. Is the solution to just avoid the python versions that are susceptible to this if you have to use sqlite?
