### ISSUE TITLE
form field issue

### ISSUE THREAD

**Issue by tejinderss** [jazzband/django-taggit#94]
I am using ModelForm with TaggableManager field as tags. Now the problem is whenever i use {{ form.tags }} in the template, and if we are editing that form, the value of that field is displayed as [<tagged item 1>, <tagged item 2> ...] instead of comma separated tag names like 'tag1, tag2, ...'. What could be the issue ?

**Comment by rtpg** [comment]
`{% for tag in tags %} {{ tag }} {% endfor %}` is what you're looking for
